// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/disbursal/DisbursalItemResponse.proto

package cart.client.modules.disbursal;

public final class DisbursalItemResponseOuterClass {
  private DisbursalItemResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_modules_disbursal_DisbursalItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_modules_disbursal_DisbursalItemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9cart/client/modules/disbursal/Disbursa" +
      "lItemResponse.proto\022\035cart.client.modules" +
      ".disbursal\032;cart/client/modules/disbursa" +
      "l/response/DisbursalOffer.proto\0324cart/cl" +
      "ient/modules/disbursal/response/Freebie." +
      "proto\032Jcart/client/modules/disbursal/res" +
      "ponse/DisbursalItemResponseMetaData.prot" +
      "o\032Dcart/client/modules/disbursal/respons" +
      "e/DisbursalWarningMessage.proto\0329cart/cl" +
      "ient/modules/disbursal/response/OfferMes" +
      "sage.proto\"\321\003\n\025DisbursalItemResponse\022D\n\013" +
      "freebieList\030\001 \003(\0132/.cart.client.modules." +
      "disbursal.response.Freebie\022F\n\006offers\030\002 \003" +
      "(\01326.cart.client.modules.disbursal.respo" +
      "nse.DisbursalOffer\022X\n\017warningMessages\030\003 " +
      "\003(\0132?.cart.client.modules.disbursal.resp" +
      "onse.DisbursalWarningMessage\022d\n\025disbursa" +
      "lItemMetaData\030\004 \001(\0132E.cart.client.module" +
      "s.disbursal.response.DisbursalItemRespon" +
      "seMetaData\022O\n\021itemOfferMessages\030\005 \003(\01324." +
      "cart.client.modules.disbursal.response.O" +
      "fferMessage\022\031\n\021freebieItemRefIds\030\006 \003(\tB!" +
      "\n\035cart.client.modules.disbursalP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cart.client.modules.disbursal.response.DisbursalOfferOuterClass.getDescriptor(),
          cart.client.modules.disbursal.response.FreebieOuterClass.getDescriptor(),
          cart.client.modules.disbursal.response.DisbursalItemResponseMetaDataOuterClass.getDescriptor(),
          cart.client.modules.disbursal.response.DisbursalWarningMessageOuterClass.getDescriptor(),
          cart.client.modules.disbursal.response.OfferMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cart_client_modules_disbursal_DisbursalItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_modules_disbursal_DisbursalItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_modules_disbursal_DisbursalItemResponse_descriptor,
        new java.lang.String[] { "FreebieList", "Offers", "WarningMessages", "DisbursalItemMetaData", "ItemOfferMessages", "FreebieItemRefIds", });
    cart.client.modules.disbursal.response.DisbursalOfferOuterClass.getDescriptor();
    cart.client.modules.disbursal.response.FreebieOuterClass.getDescriptor();
    cart.client.modules.disbursal.response.DisbursalItemResponseMetaDataOuterClass.getDescriptor();
    cart.client.modules.disbursal.response.DisbursalWarningMessageOuterClass.getDescriptor();
    cart.client.modules.disbursal.response.OfferMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
