// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/disbursal/PZDataBag.proto

package cart.client.modules.disbursal;

public interface PZDataBagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.client.modules.disbursal.PZDataBag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail pboOfferDetails = 1;</code>
   */
  java.util.List<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail> 
      getPboOfferDetailsList();
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail pboOfferDetails = 1;</code>
   */
  cart.client.modules.disbursal.response.DisbursalPBOOfferDetail getPboOfferDetails(int index);
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail pboOfferDetails = 1;</code>
   */
  int getPboOfferDetailsCount();
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail pboOfferDetails = 1;</code>
   */
  java.util.List<? extends cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOrBuilder> 
      getPboOfferDetailsOrBuilderList();
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail pboOfferDetails = 1;</code>
   */
  cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOrBuilder getPboOfferDetailsOrBuilder(
      int index);
}
