// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneof/oneof.proto

package com.flipkart.protobuf.ext.example.oneof;

public final class Oneof {
  private Oneof() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021oneof/oneof.proto\"D\n\rSampleMessage\022\023\n\t" +
      "message_1\030\001 \001(\tH\000\022\023\n\tmessage_2\030\002 \001(\tH\000B\t" +
      "\n\007messageB+\n\'com.flipkart.protobuf.ext.e" +
      "xample.oneofP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SampleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleMessage_descriptor,
        new java.lang.String[] { "Message1", "Message2", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
