// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/adjustments/enums/AdjustmentSourceType.proto

package cart.client.modules.adjustments.enums;

/**
 * Protobuf enum {@code cart.client.modules.adjustments.enums.AdjustmentSourceType}
 */
public enum AdjustmentSourceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OFFERS = 0;</code>
   */
  OFFERS(0),
  /**
   * <code>SERVICEABILITY = 1;</code>
   */
  SERVICEABILITY(1),
  /**
   * <code>PRODUCT_INFO = 2;</code>
   */
  PRODUCT_INFO(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OFFERS = 0;</code>
   */
  public static final int OFFERS_VALUE = 0;
  /**
   * <code>SERVICEABILITY = 1;</code>
   */
  public static final int SERVICEABILITY_VALUE = 1;
  /**
   * <code>PRODUCT_INFO = 2;</code>
   */
  public static final int PRODUCT_INFO_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AdjustmentSourceType valueOf(int value) {
    return forNumber(value);
  }

  public static AdjustmentSourceType forNumber(int value) {
    switch (value) {
      case 0: return OFFERS;
      case 1: return SERVICEABILITY;
      case 2: return PRODUCT_INFO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AdjustmentSourceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AdjustmentSourceType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AdjustmentSourceType>() {
          public AdjustmentSourceType findValueByNumber(int number) {
            return AdjustmentSourceType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return cart.client.modules.adjustments.enums.AdjustmentSourceTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final AdjustmentSourceType[] VALUES = values();

  public static AdjustmentSourceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AdjustmentSourceType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:cart.client.modules.adjustments.enums.AdjustmentSourceType)
}

