// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/v2/datamodels/MarketPlaceMetaData.proto

package cart.client.v2.datamodels;

public final class MarketPlaceMetaDataOuterClass {
  private MarketPlaceMetaDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_shippingD2REntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_shippingD2REntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3cart/client/v2/datamodels/MarketPlaceM" +
      "etaData.proto\022\031cart.client.v2.datamodels" +
      "\0325cart/client/v2/datamodels/MinimumBuyab" +
      "ilityInfo.proto\0328cart/client/endpoints/c" +
      "ommon/meta/cart/ListingTier.proto\032;cart/" +
      "client/modules/serviceability/ServiceAbi" +
      "lityInfo.proto\0325cart/client/endpoints/co" +
      "mmon/meta/cart/D2Rvalue.proto\0329cart/clie" +
      "nt/modules/disbursal/response/OfferMessa" +
      "ge.proto\"\255\004\n\023MarketPlaceMetaData\022R\n\022serv" +
      "iceAbilityInfo\030\001 \001(\01326.cart.client.modul" +
      "es.serviceability.ServiceAbilityInfo\022O\n\025" +
      "minimumBuyabilityInfo\030\003 \001(\01320.cart.clien" +
      "t.v2.datamodels.MinimumBuyabilityInfo\022 \n" +
      "\030isMarketPlaceServiceable\030\004 \001(\010\022M\n\017offer" +
      "D2RMessage\030\006 \001(\01324.cart.client.modules.d" +
      "isbursal.response.OfferMessage\022\022\n\nd2RMes" +
      "sage\030\007 \001(\t\022T\n\013shippingD2R\030\010 \003(\0132?.cart.c" +
      "lient.v2.datamodels.MarketPlaceMetaData." +
      "shippingD2REntry\032\225\001\n\020shippingD2REntry\022@\n" +
      "\003key\030\001 \001(\01623.cart.client.endpoints.commo" +
      "n.meta.cart.ListingTier\022?\n\005value\030\002 \001(\01320" +
      ".cart.client.endpoints.common.meta.cart." +
      "D2RvalueB\035\n\031cart.client.v2.datamodelsP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cart.client.v2.datamodels.MinimumBuyabilityInfoOuterClass.getDescriptor(),
          cart.client.endpoints.common.meta.cart.ListingTierOuterClass.getDescriptor(),
          cart.client.modules.serviceability.ServiceAbilityInfoOuterClass.getDescriptor(),
          cart.client.endpoints.common.meta.cart.D2RvalueOuterClass.getDescriptor(),
          cart.client.modules.disbursal.response.OfferMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_descriptor,
        new java.lang.String[] { "ServiceAbilityInfo", "MinimumBuyabilityInfo", "IsMarketPlaceServiceable", "OfferD2RMessage", "D2RMessage", "ShippingD2R", });
    internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_shippingD2REntry_descriptor =
      internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_descriptor.getNestedTypes().get(0);
    internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_shippingD2REntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_v2_datamodels_MarketPlaceMetaData_shippingD2REntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    cart.client.v2.datamodels.MinimumBuyabilityInfoOuterClass.getDescriptor();
    cart.client.endpoints.common.meta.cart.ListingTierOuterClass.getDescriptor();
    cart.client.modules.serviceability.ServiceAbilityInfoOuterClass.getDescriptor();
    cart.client.endpoints.common.meta.cart.D2RvalueOuterClass.getDescriptor();
    cart.client.modules.disbursal.response.OfferMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
