// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/v2/datamodels/MinimumBuyabilityInfo.proto

package cart.client.v2.datamodels;

public final class MinimumBuyabilityInfoOuterClass {
  private MinimumBuyabilityInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_v2_datamodels_MinimumBuyabilityInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_v2_datamodels_MinimumBuyabilityInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5cart/client/v2/datamodels/MinimumBuyab" +
      "ilityInfo.proto\022\031cart.client.v2.datamode" +
      "ls\"1\n\025MinimumBuyabilityInfo\022\030\n\020minPurcha" +
      "seValue\030\001 \001(\001B\035\n\031cart.client.v2.datamode" +
      "lsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cart_client_v2_datamodels_MinimumBuyabilityInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_v2_datamodels_MinimumBuyabilityInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_v2_datamodels_MinimumBuyabilityInfo_descriptor,
        new java.lang.String[] { "MinPurchaseValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
