// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/productinfo/MinimalItemInfo.proto

package cart.client.modules.productinfo;

public final class MinimalItemInfoOuterClass {
  private MinimalItemInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_modules_productinfo_MinimalItemInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_modules_productinfo_MinimalItemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5cart/client/modules/productinfo/Minima" +
      "lItemInfo.proto\022\037cart.client.modules.pro" +
      "ductinfo\"Q\n\017MinimalItemInfo\022\r\n\005title\030\001 \001" +
      "(\t\022\013\n\003url\030\002 \001(\t\022\020\n\010imageUrl\030\003 \001(\t\022\020\n\010ver" +
      "tical\030\004 \001(\tB#\n\037cart.client.modules.produ" +
      "ctinfoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cart_client_modules_productinfo_MinimalItemInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_modules_productinfo_MinimalItemInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_modules_productinfo_MinimalItemInfo_descriptor,
        new java.lang.String[] { "Title", "Url", "ImageUrl", "Vertical", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
