// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/serviceability/enums/DeliverySpeedTypeEnum.proto

package cart.client.modules.serviceability.enums;

public final class DeliverySpeedTypeEnumOuterClass {
  private DeliverySpeedTypeEnumOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDcart/client/modules/serviceability/enu" +
      "ms/DeliverySpeedTypeEnum.proto\022(cart.cli" +
      "ent.modules.serviceability.enums*>\n\025Deli" +
      "verySpeedTypeEnum\022\013\n\007EXPRESS\020\000\022\013\n\007REGULA" +
      "R\020\001\022\013\n\007PREMIUM\020\002B,\n(cart.client.modules." +
      "serviceability.enumsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
