// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/v2/endpoints/common/meta/cartitem/SelectedServiceInfo.proto

package cart.client.v2.endpoints.common.meta.cartitem;

public final class SelectedServiceInfoOuterClass {
  private SelectedServiceInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_v2_endpoints_common_meta_cartitem_SelectedServiceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_v2_endpoints_common_meta_cartitem_SelectedServiceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nGcart/client/v2/endpoints/common/meta/c" +
      "artitem/SelectedServiceInfo.proto\022-cart." +
      "client.v2.endpoints.common.meta.cartitem" +
      "\032<cart/client/endpoints/common/meta/cart" +
      "item/ServiceType.proto\032-cart/client/modu" +
      "les/serviceability/Slot.proto\032:cart/clie" +
      "nt/endpoints/common/meta/cartitem/Update" +
      "dBy.proto\0320cart/client/endpoints/common/" +
      "meta/Giftwrap.proto\"\252\002\n\023SelectedServiceI" +
      "nfo\022E\n\004type\030\001 \001(\01627.cart.client.endpoint" +
      "s.common.meta.cartitem.ServiceType\022\r\n\005va" +
      "lue\030\002 \001(\t\022;\n\006gwInfo\030\003 \001(\0132+.cart.client." +
      "endpoints.common.meta.Giftwrap\022H\n\tupdate" +
      "dBy\030\004 \001(\01625.cart.client.endpoints.common" +
      ".meta.cartitem.UpdatedBy\0226\n\004slot\030\005 \001(\0132(" +
      ".cart.client.modules.serviceability.Slot" +
      "B1\n-cart.client.v2.endpoints.common.meta" +
      ".cartitemP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cart.client.endpoints.common.meta.cartitem.ServiceTypeOuterClass.getDescriptor(),
          cart.client.modules.serviceability.SlotOuterClass.getDescriptor(),
          cart.client.endpoints.common.meta.cartitem.UpdatedByOuterClass.getDescriptor(),
          cart.client.endpoints.common.meta.GiftwrapOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cart_client_v2_endpoints_common_meta_cartitem_SelectedServiceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_v2_endpoints_common_meta_cartitem_SelectedServiceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_v2_endpoints_common_meta_cartitem_SelectedServiceInfo_descriptor,
        new java.lang.String[] { "Type", "Value", "GwInfo", "UpdatedBy", "Slot", });
    cart.client.endpoints.common.meta.cartitem.ServiceTypeOuterClass.getDescriptor();
    cart.client.modules.serviceability.SlotOuterClass.getDescriptor();
    cart.client.endpoints.common.meta.cartitem.UpdatedByOuterClass.getDescriptor();
    cart.client.endpoints.common.meta.GiftwrapOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
