// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plain_message.proto

package com.flipkart.protobuf.ext.generator.test.sample;

public interface PlainMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PlainMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double double1 = 1;</code>
   */
  double getDouble1();

  /**
   * <code>float float1 = 2;</code>
   */
  float getFloat1();

  /**
   * <code>int32 int1 = 3;</code>
   */
  int getInt1();

  /**
   * <code>int64 long1 = 4;</code>
   */
  long getLong1();

  /**
   * <code>bool boolean1 = 5;</code>
   */
  boolean getBoolean1();

  /**
   * <code>string string1 = 6;</code>
   */
  java.lang.String getString1();
  /**
   * <code>string string1 = 6;</code>
   */
  com.google.protobuf.ByteString
      getString1Bytes();

  /**
   * <code>double double2 = 7;</code>
   */
  double getDouble2();

  /**
   * <code>float float2 = 8;</code>
   */
  float getFloat2();

  /**
   * <code>int32 int2 = 9;</code>
   */
  int getInt2();

  /**
   * <code>int64 long2 = 10;</code>
   */
  long getLong2();

  /**
   * <code>bool boolean2 = 11;</code>
   */
  boolean getBoolean2();
}
