// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/flipkart/protobuf/ext/generator/test/sample/SampleEnumType.proto

package com.flipkart.protobuf.ext.generator.test.sample;

/**
 * Protobuf enum {@code com.flipkart.protobuf.ext.generator.test.sample.SampleEnumType}
 */
public enum SampleEnumType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MOBILE = 0;</code>
   */
  MOBILE(0),
  /**
   * <code>HOME = 1;</code>
   */
  HOME(1),
  /**
   * <code>WORK = 2;</code>
   */
  WORK(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MOBILE = 0;</code>
   */
  public static final int MOBILE_VALUE = 0;
  /**
   * <code>HOME = 1;</code>
   */
  public static final int HOME_VALUE = 1;
  /**
   * <code>WORK = 2;</code>
   */
  public static final int WORK_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SampleEnumType valueOf(int value) {
    return forNumber(value);
  }

  public static SampleEnumType forNumber(int value) {
    switch (value) {
      case 0: return MOBILE;
      case 1: return HOME;
      case 2: return WORK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SampleEnumType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SampleEnumType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SampleEnumType>() {
          public SampleEnumType findValueByNumber(int number) {
            return SampleEnumType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.flipkart.protobuf.ext.generator.test.sample.SampleEnumTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final SampleEnumType[] VALUES = values();

  public static SampleEnumType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SampleEnumType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.flipkart.protobuf.ext.generator.test.sample.SampleEnumType)
}

