// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.flipkart.protobuf.ext.generator.test.sample;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flipkart_protobuf_ext_generator_test_sample_PlainMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flipkart_protobuf_ext_generator_test_sample_PlainMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022/com.flipkart.protobuf.ext." +
      "generator.test.sample\032\037google/protobuf/t" +
      "imestamp.proto\"\355\001\n\014PlainMessage\022\017\n\007doubl" +
      "e1\030\001 \001(\001\022\016\n\006float1\030\002 \001(\002\022\014\n\004int1\030\003 \001(\005\022\r" +
      "\n\005long1\030\004 \001(\003\022\020\n\010boolean1\030\005 \001(\010\022\017\n\007strin" +
      "g1\030\006 \001(\t\022,\n\010dateTime\030\007 \001(\0132\032.google.prot" +
      "obuf.Timestamp\022\017\n\007double2\030\010 \001(\001\022\016\n\006float" +
      "2\030\t \001(\002\022\014\n\004int2\030\n \001(\005\022\r\n\005long2\030\013 \001(\003\022\020\n\010" +
      "boolean2\030\014 \001(\010B3\n/com.flipkart.protobuf." +
      "ext.generator.test.sampleP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_flipkart_protobuf_ext_generator_test_sample_PlainMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_flipkart_protobuf_ext_generator_test_sample_PlainMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flipkart_protobuf_ext_generator_test_sample_PlainMessage_descriptor,
        new java.lang.String[] { "Double1", "Float1", "Int1", "Long1", "Boolean1", "String1", "DateTime", "Double2", "Float2", "Int2", "Long2", "Boolean2", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
