// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/endpoints/common/meta/Giftwrap.proto

package cart.client.endpoints.common.meta;

public final class GiftwrapOuterClass {
  private GiftwrapOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_endpoints_common_meta_Giftwrap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_endpoints_common_meta_Giftwrap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0cart/client/endpoints/common/meta/Gift" +
      "wrap.proto\022!cart.client.endpoints.common" +
      ".meta\"H\n\010Giftwrap\022\n\n\002to\030\001 \001(\t\022\014\n\004from\030\002 " +
      "\001(\t\022\017\n\007message\030\003 \001(\t\022\021\n\tisChecked\030\004 \001(\010B" +
      "%\n!cart.client.endpoints.common.metaP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cart_client_endpoints_common_meta_Giftwrap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_endpoints_common_meta_Giftwrap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_endpoints_common_meta_Giftwrap_descriptor,
        new java.lang.String[] { "To", "From", "Message", "IsChecked", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
