// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/disbursal/response/DisbursalPBOOfferDetail.proto

package cart.client.modules.disbursal.response;

/**
 * Protobuf type {@code cart.client.modules.disbursal.response.DisbursalPBOOfferDetail}
 */
public  final class DisbursalPBOOfferDetail extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail)
    DisbursalPBOOfferDetailOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DisbursalPBOOfferDetail.newBuilder() to construct.
  private DisbursalPBOOfferDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DisbursalPBOOfferDetail() {
    offerId_ = "";
    metadata_ = java.util.Collections.emptyList();
    offerItemAmount_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DisbursalPBOOfferDetail(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            offerId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              metadata_ = new java.util.ArrayList<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry>();
              mutable_bitField0_ |= 0x00000002;
            }
            metadata_.add(
                input.readMessage(cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.parser(), extensionRegistry));
            break;
          }
          case 24: {

            offerItemAmount_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        metadata_ = java.util.Collections.unmodifiableList(metadata_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.class, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.Builder.class);
  }

  public interface metadataEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry}
   */
  public  static final class metadataEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry)
      metadataEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use metadataEntry.newBuilder() to construct.
    private metadataEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private metadataEntry() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private metadataEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_metadataEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_metadataEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.class, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry)) {
        return super.equals(obj);
      }
      cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry other = (cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getValue()
          .equals(other.getValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry)
        cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_metadataEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_metadataEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.class, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder.class);
      }

      // Construct using cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_metadataEntry_descriptor;
      }

      public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry getDefaultInstanceForType() {
        return cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.getDefaultInstance();
      }

      public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry build() {
        cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry buildPartial() {
        cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry result = new cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry(this);
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry) {
          return mergeFrom((cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry other) {
        if (other == cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry)
    }

    // @@protoc_insertion_point(class_scope:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry)
    private static final cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry();
    }

    public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<metadataEntry>
        PARSER = new com.google.protobuf.AbstractParser<metadataEntry>() {
      public metadataEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new metadataEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<metadataEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<metadataEntry> getParserForType() {
      return PARSER;
    }

    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int OFFERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object offerId_;
  /**
   * <code>string offerId = 1;</code>
   */
  public java.lang.String getOfferId() {
    java.lang.Object ref = offerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      offerId_ = s;
      return s;
    }
  }
  /**
   * <code>string offerId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOfferIdBytes() {
    java.lang.Object ref = offerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      offerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 2;
  private java.util.List<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry> metadata_;
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
   */
  public java.util.List<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry> getMetadataList() {
    return metadata_;
  }
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
   */
  public java.util.List<? extends cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder> 
      getMetadataOrBuilderList() {
    return metadata_;
  }
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
   */
  public int getMetadataCount() {
    return metadata_.size();
  }
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
   */
  public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry getMetadata(int index) {
    return metadata_.get(index);
  }
  /**
   * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
   */
  public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder getMetadataOrBuilder(
      int index) {
    return metadata_.get(index);
  }

  public static final int OFFERITEMAMOUNT_FIELD_NUMBER = 3;
  private int offerItemAmount_;
  /**
   * <code>int32 offerItemAmount = 3;</code>
   */
  public int getOfferItemAmount() {
    return offerItemAmount_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOfferIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, offerId_);
    }
    for (int i = 0; i < metadata_.size(); i++) {
      output.writeMessage(2, metadata_.get(i));
    }
    if (offerItemAmount_ != 0) {
      output.writeInt32(3, offerItemAmount_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOfferIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, offerId_);
    }
    for (int i = 0; i < metadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, metadata_.get(i));
    }
    if (offerItemAmount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, offerItemAmount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cart.client.modules.disbursal.response.DisbursalPBOOfferDetail)) {
      return super.equals(obj);
    }
    cart.client.modules.disbursal.response.DisbursalPBOOfferDetail other = (cart.client.modules.disbursal.response.DisbursalPBOOfferDetail) obj;

    boolean result = true;
    result = result && getOfferId()
        .equals(other.getOfferId());
    result = result && getMetadataList()
        .equals(other.getMetadataList());
    result = result && (getOfferItemAmount()
        == other.getOfferItemAmount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OFFERID_FIELD_NUMBER;
    hash = (53 * hash) + getOfferId().hashCode();
    if (getMetadataCount() > 0) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataList().hashCode();
    }
    hash = (37 * hash) + OFFERITEMAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getOfferItemAmount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cart.client.modules.disbursal.response.DisbursalPBOOfferDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cart.client.modules.disbursal.response.DisbursalPBOOfferDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail)
      cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.class, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.Builder.class);
    }

    // Construct using cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadataFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      offerId_ = "";

      if (metadataBuilder_ == null) {
        metadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        metadataBuilder_.clear();
      }
      offerItemAmount_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cart.client.modules.disbursal.response.DisbursalPBOOfferDetailOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalPBOOfferDetail_descriptor;
    }

    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail getDefaultInstanceForType() {
      return cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.getDefaultInstance();
    }

    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail build() {
      cart.client.modules.disbursal.response.DisbursalPBOOfferDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail buildPartial() {
      cart.client.modules.disbursal.response.DisbursalPBOOfferDetail result = new cart.client.modules.disbursal.response.DisbursalPBOOfferDetail(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.offerId_ = offerId_;
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          metadata_ = java.util.Collections.unmodifiableList(metadata_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      result.offerItemAmount_ = offerItemAmount_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cart.client.modules.disbursal.response.DisbursalPBOOfferDetail) {
        return mergeFrom((cart.client.modules.disbursal.response.DisbursalPBOOfferDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cart.client.modules.disbursal.response.DisbursalPBOOfferDetail other) {
      if (other == cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.getDefaultInstance()) return this;
      if (!other.getOfferId().isEmpty()) {
        offerId_ = other.offerId_;
        onChanged();
      }
      if (metadataBuilder_ == null) {
        if (!other.metadata_.isEmpty()) {
          if (metadata_.isEmpty()) {
            metadata_ = other.metadata_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMetadataIsMutable();
            metadata_.addAll(other.metadata_);
          }
          onChanged();
        }
      } else {
        if (!other.metadata_.isEmpty()) {
          if (metadataBuilder_.isEmpty()) {
            metadataBuilder_.dispose();
            metadataBuilder_ = null;
            metadata_ = other.metadata_;
            bitField0_ = (bitField0_ & ~0x00000002);
            metadataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetadataFieldBuilder() : null;
          } else {
            metadataBuilder_.addAllMessages(other.metadata_);
          }
        }
      }
      if (other.getOfferItemAmount() != 0) {
        setOfferItemAmount(other.getOfferItemAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cart.client.modules.disbursal.response.DisbursalPBOOfferDetail parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cart.client.modules.disbursal.response.DisbursalPBOOfferDetail) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object offerId_ = "";
    /**
     * <code>string offerId = 1;</code>
     */
    public java.lang.String getOfferId() {
      java.lang.Object ref = offerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        offerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string offerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOfferIdBytes() {
      java.lang.Object ref = offerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        offerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string offerId = 1;</code>
     */
    public Builder setOfferId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      offerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string offerId = 1;</code>
     */
    public Builder clearOfferId() {
      
      offerId_ = getDefaultInstance().getOfferId();
      onChanged();
      return this;
    }
    /**
     * <code>string offerId = 1;</code>
     */
    public Builder setOfferIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      offerId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry> metadata_ =
      java.util.Collections.emptyList();
    private void ensureMetadataIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        metadata_ = new java.util.ArrayList<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry>(metadata_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder> metadataBuilder_;

    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public java.util.List<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry> getMetadataList() {
      if (metadataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metadata_);
      } else {
        return metadataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public int getMetadataCount() {
      if (metadataBuilder_ == null) {
        return metadata_.size();
      } else {
        return metadataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry getMetadata(int index) {
      if (metadataBuilder_ == null) {
        return metadata_.get(index);
      } else {
        return metadataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder setMetadata(
        int index, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.set(index, value);
        onChanged();
      } else {
        metadataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder setMetadata(
        int index, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.set(index, builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder addMetadata(cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.add(value);
        onChanged();
      } else {
        metadataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder addMetadata(
        int index, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataIsMutable();
        metadata_.add(index, value);
        onChanged();
      } else {
        metadataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder addMetadata(
        cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.add(builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder addMetadata(
        int index, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.add(index, builderForValue.build());
        onChanged();
      } else {
        metadataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder addAllMetadata(
        java.lang.Iterable<? extends cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry> values) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metadata_);
        onChanged();
      } else {
        metadataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        metadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public Builder removeMetadata(int index) {
      if (metadataBuilder_ == null) {
        ensureMetadataIsMutable();
        metadata_.remove(index);
        onChanged();
      } else {
        metadataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder getMetadataBuilder(
        int index) {
      return getMetadataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder getMetadataOrBuilder(
        int index) {
      if (metadataBuilder_ == null) {
        return metadata_.get(index);  } else {
        return metadataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public java.util.List<? extends cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder> 
         getMetadataOrBuilderList() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metadata_);
      }
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder addMetadataBuilder() {
      return getMetadataFieldBuilder().addBuilder(
          cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder addMetadataBuilder(
        int index) {
      return getMetadataFieldBuilder().addBuilder(
          index, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry metadata = 2;</code>
     */
    public java.util.List<cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder> 
         getMetadataBuilderList() {
      return getMetadataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntry.Builder, cart.client.modules.disbursal.response.DisbursalPBOOfferDetail.metadataEntryOrBuilder>(
                metadata_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private int offerItemAmount_ ;
    /**
     * <code>int32 offerItemAmount = 3;</code>
     */
    public int getOfferItemAmount() {
      return offerItemAmount_;
    }
    /**
     * <code>int32 offerItemAmount = 3;</code>
     */
    public Builder setOfferItemAmount(int value) {
      
      offerItemAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 offerItemAmount = 3;</code>
     */
    public Builder clearOfferItemAmount() {
      
      offerItemAmount_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail)
  }

  // @@protoc_insertion_point(class_scope:cart.client.modules.disbursal.response.DisbursalPBOOfferDetail)
  private static final cart.client.modules.disbursal.response.DisbursalPBOOfferDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cart.client.modules.disbursal.response.DisbursalPBOOfferDetail();
  }

  public static cart.client.modules.disbursal.response.DisbursalPBOOfferDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DisbursalPBOOfferDetail>
      PARSER = new com.google.protobuf.AbstractParser<DisbursalPBOOfferDetail>() {
    public DisbursalPBOOfferDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DisbursalPBOOfferDetail(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DisbursalPBOOfferDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DisbursalPBOOfferDetail> getParserForType() {
    return PARSER;
  }

  public cart.client.modules.disbursal.response.DisbursalPBOOfferDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

