// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/distancetoredemption/ProductContext.proto

package cart.client.modules.distancetoredemption;

public interface ProductContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.client.modules.distancetoredemption.ProductContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productId = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string listingId = 2;</code>
   */
  java.lang.String getListingId();
  /**
   * <code>string listingId = 2;</code>
   */
  com.google.protobuf.ByteString
      getListingIdBytes();

  /**
   * <code>string sellerId = 3;</code>
   */
  java.lang.String getSellerId();
  /**
   * <code>string sellerId = 3;</code>
   */
  com.google.protobuf.ByteString
      getSellerIdBytes();

  /**
   * <code>string productTitle = 4;</code>
   */
  java.lang.String getProductTitle();
  /**
   * <code>string productTitle = 4;</code>
   */
  com.google.protobuf.ByteString
      getProductTitleBytes();
}
