// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/endpoints/common/meta/cart/FulfillmentData.proto

package cart.client.endpoints.common.meta.cart;

public final class FulfillmentDataOuterClass {
  private FulfillmentDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_endpoints_common_meta_cart_FulfillmentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_endpoints_common_meta_cart_FulfillmentData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<cart/client/endpoints/common/meta/cart" +
      "/FulfillmentData.proto\022&cart.client.endp" +
      "oints.common.meta.cart\032?cart/client/endp" +
      "oints/common/enums/FulfillmentServiceTyp" +
      "e.proto\"\204\001\n\017FulfillmentData\022Z\n\026fulfillme" +
      "ntServiceType\030\001 \001(\0162:.cart.client.endpoi" +
      "nts.common.enums.FulfillmentServiceType\022" +
      "\025\n\rfulfillmentId\030\002 \001(\tB*\n&cart.client.en" +
      "dpoints.common.meta.cartP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cart.client.endpoints.common.enums.FulfillmentServiceTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cart_client_endpoints_common_meta_cart_FulfillmentData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_endpoints_common_meta_cart_FulfillmentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_endpoints_common_meta_cart_FulfillmentData_descriptor,
        new java.lang.String[] { "FulfillmentServiceType", "FulfillmentId", });
    cart.client.endpoints.common.enums.FulfillmentServiceTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
