// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/flipkart/lockin/model/api/LockinUserStateResponse.proto

package com.flipkart.lockin.model.api;

public interface LockinUserStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.flipkart.lockin.model.api.LockinUserStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountId = 1;</code>
   */
  java.lang.String getAccountId();
  /**
   * <code>string accountId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <code>.com.flipkart.lockin.enums.MembershipStatus membershipStatus = 2;</code>
   */
  int getMembershipStatusValue();
  /**
   * <code>.com.flipkart.lockin.enums.MembershipStatus membershipStatus = 2;</code>
   */
  com.flipkart.lockin.enums.MembershipStatus getMembershipStatus();

  /**
   * <code>.com.flipkart.lockin.model.membership.MembershipTenureInfo currentTenure = 3;</code>
   */
  boolean hasCurrentTenure();
  /**
   * <code>.com.flipkart.lockin.model.membership.MembershipTenureInfo currentTenure = 3;</code>
   */
  com.flipkart.lockin.model.membership.MembershipTenureInfo getCurrentTenure();
  /**
   * <code>.com.flipkart.lockin.model.membership.MembershipTenureInfo currentTenure = 3;</code>
   */
  com.flipkart.lockin.model.membership.MembershipTenureInfoOrBuilder getCurrentTenureOrBuilder();

  /**
   * <code>string memberSince = 4;</code>
   */
  java.lang.String getMemberSince();
  /**
   * <code>string memberSince = 4;</code>
   */
  com.google.protobuf.ByteString
      getMemberSinceBytes();

  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit eligibleBenefits = 5;</code>
   */
  java.util.List<com.flipkart.lockin.enums.Benefit> getEligibleBenefitsList();
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit eligibleBenefits = 5;</code>
   */
  int getEligibleBenefitsCount();
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit eligibleBenefits = 5;</code>
   */
  com.flipkart.lockin.enums.Benefit getEligibleBenefits(int index);
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit eligibleBenefits = 5;</code>
   */
  java.util.List<java.lang.Integer>
  getEligibleBenefitsValueList();
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit eligibleBenefits = 5;</code>
   */
  int getEligibleBenefitsValue(int index);

  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit potentialBenefits = 6;</code>
   */
  java.util.List<com.flipkart.lockin.enums.Benefit> getPotentialBenefitsList();
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit potentialBenefits = 6;</code>
   */
  int getPotentialBenefitsCount();
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit potentialBenefits = 6;</code>
   */
  com.flipkart.lockin.enums.Benefit getPotentialBenefits(int index);
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit potentialBenefits = 6;</code>
   */
  java.util.List<java.lang.Integer>
  getPotentialBenefitsValueList();
  /**
   * <code>repeated .com.flipkart.lockin.enums.Benefit potentialBenefits = 6;</code>
   */
  int getPotentialBenefitsValue(int index);
}
