// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/serviceability/ServiceAbilityInfo.proto

package cart.client.modules.serviceability;

/**
 * Protobuf type {@code cart.client.modules.serviceability.ServiceAbilityInfo}
 */
public  final class ServiceAbilityInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cart.client.modules.serviceability.ServiceAbilityInfo)
    ServiceAbilityInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceAbilityInfo.newBuilder() to construct.
  private ServiceAbilityInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceAbilityInfo() {
    coreServices_ = java.util.Collections.emptyList();
    addOnServices_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceAbilityInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              coreServices_ = new java.util.ArrayList<cart.client.modules.serviceability.Service>();
              mutable_bitField0_ |= 0x00000001;
            }
            coreServices_.add(
                input.readMessage(cart.client.modules.serviceability.Service.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              addOnServices_ = new java.util.ArrayList<cart.client.modules.serviceability.Service>();
              mutable_bitField0_ |= 0x00000002;
            }
            addOnServices_.add(
                input.readMessage(cart.client.modules.serviceability.Service.parser(), extensionRegistry));
            break;
          }
          case 26: {
            cart.client.modules.serviceability.ServiceabilityInfoMetaData.Builder subBuilder = null;
            if (metaData_ != null) {
              subBuilder = metaData_.toBuilder();
            }
            metaData_ = input.readMessage(cart.client.modules.serviceability.ServiceabilityInfoMetaData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metaData_);
              metaData_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        coreServices_ = java.util.Collections.unmodifiableList(coreServices_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        addOnServices_ = java.util.Collections.unmodifiableList(addOnServices_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cart.client.modules.serviceability.ServiceAbilityInfoOuterClass.internal_static_cart_client_modules_serviceability_ServiceAbilityInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cart.client.modules.serviceability.ServiceAbilityInfoOuterClass.internal_static_cart_client_modules_serviceability_ServiceAbilityInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cart.client.modules.serviceability.ServiceAbilityInfo.class, cart.client.modules.serviceability.ServiceAbilityInfo.Builder.class);
  }

  private int bitField0_;
  public static final int CORESERVICES_FIELD_NUMBER = 1;
  private java.util.List<cart.client.modules.serviceability.Service> coreServices_;
  /**
   * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
   */
  public java.util.List<cart.client.modules.serviceability.Service> getCoreServicesList() {
    return coreServices_;
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
   */
  public java.util.List<? extends cart.client.modules.serviceability.ServiceOrBuilder> 
      getCoreServicesOrBuilderList() {
    return coreServices_;
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
   */
  public int getCoreServicesCount() {
    return coreServices_.size();
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
   */
  public cart.client.modules.serviceability.Service getCoreServices(int index) {
    return coreServices_.get(index);
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
   */
  public cart.client.modules.serviceability.ServiceOrBuilder getCoreServicesOrBuilder(
      int index) {
    return coreServices_.get(index);
  }

  public static final int ADDONSERVICES_FIELD_NUMBER = 2;
  private java.util.List<cart.client.modules.serviceability.Service> addOnServices_;
  /**
   * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
   */
  public java.util.List<cart.client.modules.serviceability.Service> getAddOnServicesList() {
    return addOnServices_;
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
   */
  public java.util.List<? extends cart.client.modules.serviceability.ServiceOrBuilder> 
      getAddOnServicesOrBuilderList() {
    return addOnServices_;
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
   */
  public int getAddOnServicesCount() {
    return addOnServices_.size();
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
   */
  public cart.client.modules.serviceability.Service getAddOnServices(int index) {
    return addOnServices_.get(index);
  }
  /**
   * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
   */
  public cart.client.modules.serviceability.ServiceOrBuilder getAddOnServicesOrBuilder(
      int index) {
    return addOnServices_.get(index);
  }

  public static final int METADATA_FIELD_NUMBER = 3;
  private cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData_;
  /**
   * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
   */
  public boolean hasMetaData() {
    return metaData_ != null;
  }
  /**
   * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
   */
  public cart.client.modules.serviceability.ServiceabilityInfoMetaData getMetaData() {
    return metaData_ == null ? cart.client.modules.serviceability.ServiceabilityInfoMetaData.getDefaultInstance() : metaData_;
  }
  /**
   * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
   */
  public cart.client.modules.serviceability.ServiceabilityInfoMetaDataOrBuilder getMetaDataOrBuilder() {
    return getMetaData();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < coreServices_.size(); i++) {
      output.writeMessage(1, coreServices_.get(i));
    }
    for (int i = 0; i < addOnServices_.size(); i++) {
      output.writeMessage(2, addOnServices_.get(i));
    }
    if (metaData_ != null) {
      output.writeMessage(3, getMetaData());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < coreServices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, coreServices_.get(i));
    }
    for (int i = 0; i < addOnServices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, addOnServices_.get(i));
    }
    if (metaData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMetaData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cart.client.modules.serviceability.ServiceAbilityInfo)) {
      return super.equals(obj);
    }
    cart.client.modules.serviceability.ServiceAbilityInfo other = (cart.client.modules.serviceability.ServiceAbilityInfo) obj;

    boolean result = true;
    result = result && getCoreServicesList()
        .equals(other.getCoreServicesList());
    result = result && getAddOnServicesList()
        .equals(other.getAddOnServicesList());
    result = result && (hasMetaData() == other.hasMetaData());
    if (hasMetaData()) {
      result = result && getMetaData()
          .equals(other.getMetaData());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoreServicesCount() > 0) {
      hash = (37 * hash) + CORESERVICES_FIELD_NUMBER;
      hash = (53 * hash) + getCoreServicesList().hashCode();
    }
    if (getAddOnServicesCount() > 0) {
      hash = (37 * hash) + ADDONSERVICES_FIELD_NUMBER;
      hash = (53 * hash) + getAddOnServicesList().hashCode();
    }
    if (hasMetaData()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetaData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.serviceability.ServiceAbilityInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cart.client.modules.serviceability.ServiceAbilityInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cart.client.modules.serviceability.ServiceAbilityInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cart.client.modules.serviceability.ServiceAbilityInfo)
      cart.client.modules.serviceability.ServiceAbilityInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cart.client.modules.serviceability.ServiceAbilityInfoOuterClass.internal_static_cart_client_modules_serviceability_ServiceAbilityInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cart.client.modules.serviceability.ServiceAbilityInfoOuterClass.internal_static_cart_client_modules_serviceability_ServiceAbilityInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cart.client.modules.serviceability.ServiceAbilityInfo.class, cart.client.modules.serviceability.ServiceAbilityInfo.Builder.class);
    }

    // Construct using cart.client.modules.serviceability.ServiceAbilityInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCoreServicesFieldBuilder();
        getAddOnServicesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (coreServicesBuilder_ == null) {
        coreServices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        coreServicesBuilder_.clear();
      }
      if (addOnServicesBuilder_ == null) {
        addOnServices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        addOnServicesBuilder_.clear();
      }
      if (metaDataBuilder_ == null) {
        metaData_ = null;
      } else {
        metaData_ = null;
        metaDataBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cart.client.modules.serviceability.ServiceAbilityInfoOuterClass.internal_static_cart_client_modules_serviceability_ServiceAbilityInfo_descriptor;
    }

    public cart.client.modules.serviceability.ServiceAbilityInfo getDefaultInstanceForType() {
      return cart.client.modules.serviceability.ServiceAbilityInfo.getDefaultInstance();
    }

    public cart.client.modules.serviceability.ServiceAbilityInfo build() {
      cart.client.modules.serviceability.ServiceAbilityInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cart.client.modules.serviceability.ServiceAbilityInfo buildPartial() {
      cart.client.modules.serviceability.ServiceAbilityInfo result = new cart.client.modules.serviceability.ServiceAbilityInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (coreServicesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          coreServices_ = java.util.Collections.unmodifiableList(coreServices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.coreServices_ = coreServices_;
      } else {
        result.coreServices_ = coreServicesBuilder_.build();
      }
      if (addOnServicesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          addOnServices_ = java.util.Collections.unmodifiableList(addOnServices_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.addOnServices_ = addOnServices_;
      } else {
        result.addOnServices_ = addOnServicesBuilder_.build();
      }
      if (metaDataBuilder_ == null) {
        result.metaData_ = metaData_;
      } else {
        result.metaData_ = metaDataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cart.client.modules.serviceability.ServiceAbilityInfo) {
        return mergeFrom((cart.client.modules.serviceability.ServiceAbilityInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cart.client.modules.serviceability.ServiceAbilityInfo other) {
      if (other == cart.client.modules.serviceability.ServiceAbilityInfo.getDefaultInstance()) return this;
      if (coreServicesBuilder_ == null) {
        if (!other.coreServices_.isEmpty()) {
          if (coreServices_.isEmpty()) {
            coreServices_ = other.coreServices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoreServicesIsMutable();
            coreServices_.addAll(other.coreServices_);
          }
          onChanged();
        }
      } else {
        if (!other.coreServices_.isEmpty()) {
          if (coreServicesBuilder_.isEmpty()) {
            coreServicesBuilder_.dispose();
            coreServicesBuilder_ = null;
            coreServices_ = other.coreServices_;
            bitField0_ = (bitField0_ & ~0x00000001);
            coreServicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCoreServicesFieldBuilder() : null;
          } else {
            coreServicesBuilder_.addAllMessages(other.coreServices_);
          }
        }
      }
      if (addOnServicesBuilder_ == null) {
        if (!other.addOnServices_.isEmpty()) {
          if (addOnServices_.isEmpty()) {
            addOnServices_ = other.addOnServices_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAddOnServicesIsMutable();
            addOnServices_.addAll(other.addOnServices_);
          }
          onChanged();
        }
      } else {
        if (!other.addOnServices_.isEmpty()) {
          if (addOnServicesBuilder_.isEmpty()) {
            addOnServicesBuilder_.dispose();
            addOnServicesBuilder_ = null;
            addOnServices_ = other.addOnServices_;
            bitField0_ = (bitField0_ & ~0x00000002);
            addOnServicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAddOnServicesFieldBuilder() : null;
          } else {
            addOnServicesBuilder_.addAllMessages(other.addOnServices_);
          }
        }
      }
      if (other.hasMetaData()) {
        mergeMetaData(other.getMetaData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cart.client.modules.serviceability.ServiceAbilityInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cart.client.modules.serviceability.ServiceAbilityInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<cart.client.modules.serviceability.Service> coreServices_ =
      java.util.Collections.emptyList();
    private void ensureCoreServicesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        coreServices_ = new java.util.ArrayList<cart.client.modules.serviceability.Service>(coreServices_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cart.client.modules.serviceability.Service, cart.client.modules.serviceability.Service.Builder, cart.client.modules.serviceability.ServiceOrBuilder> coreServicesBuilder_;

    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public java.util.List<cart.client.modules.serviceability.Service> getCoreServicesList() {
      if (coreServicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(coreServices_);
      } else {
        return coreServicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public int getCoreServicesCount() {
      if (coreServicesBuilder_ == null) {
        return coreServices_.size();
      } else {
        return coreServicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public cart.client.modules.serviceability.Service getCoreServices(int index) {
      if (coreServicesBuilder_ == null) {
        return coreServices_.get(index);
      } else {
        return coreServicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder setCoreServices(
        int index, cart.client.modules.serviceability.Service value) {
      if (coreServicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoreServicesIsMutable();
        coreServices_.set(index, value);
        onChanged();
      } else {
        coreServicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder setCoreServices(
        int index, cart.client.modules.serviceability.Service.Builder builderForValue) {
      if (coreServicesBuilder_ == null) {
        ensureCoreServicesIsMutable();
        coreServices_.set(index, builderForValue.build());
        onChanged();
      } else {
        coreServicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder addCoreServices(cart.client.modules.serviceability.Service value) {
      if (coreServicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoreServicesIsMutable();
        coreServices_.add(value);
        onChanged();
      } else {
        coreServicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder addCoreServices(
        int index, cart.client.modules.serviceability.Service value) {
      if (coreServicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoreServicesIsMutable();
        coreServices_.add(index, value);
        onChanged();
      } else {
        coreServicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder addCoreServices(
        cart.client.modules.serviceability.Service.Builder builderForValue) {
      if (coreServicesBuilder_ == null) {
        ensureCoreServicesIsMutable();
        coreServices_.add(builderForValue.build());
        onChanged();
      } else {
        coreServicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder addCoreServices(
        int index, cart.client.modules.serviceability.Service.Builder builderForValue) {
      if (coreServicesBuilder_ == null) {
        ensureCoreServicesIsMutable();
        coreServices_.add(index, builderForValue.build());
        onChanged();
      } else {
        coreServicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder addAllCoreServices(
        java.lang.Iterable<? extends cart.client.modules.serviceability.Service> values) {
      if (coreServicesBuilder_ == null) {
        ensureCoreServicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coreServices_);
        onChanged();
      } else {
        coreServicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder clearCoreServices() {
      if (coreServicesBuilder_ == null) {
        coreServices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        coreServicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public Builder removeCoreServices(int index) {
      if (coreServicesBuilder_ == null) {
        ensureCoreServicesIsMutable();
        coreServices_.remove(index);
        onChanged();
      } else {
        coreServicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public cart.client.modules.serviceability.Service.Builder getCoreServicesBuilder(
        int index) {
      return getCoreServicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public cart.client.modules.serviceability.ServiceOrBuilder getCoreServicesOrBuilder(
        int index) {
      if (coreServicesBuilder_ == null) {
        return coreServices_.get(index);  } else {
        return coreServicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public java.util.List<? extends cart.client.modules.serviceability.ServiceOrBuilder> 
         getCoreServicesOrBuilderList() {
      if (coreServicesBuilder_ != null) {
        return coreServicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(coreServices_);
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public cart.client.modules.serviceability.Service.Builder addCoreServicesBuilder() {
      return getCoreServicesFieldBuilder().addBuilder(
          cart.client.modules.serviceability.Service.getDefaultInstance());
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public cart.client.modules.serviceability.Service.Builder addCoreServicesBuilder(
        int index) {
      return getCoreServicesFieldBuilder().addBuilder(
          index, cart.client.modules.serviceability.Service.getDefaultInstance());
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service coreServices = 1;</code>
     */
    public java.util.List<cart.client.modules.serviceability.Service.Builder> 
         getCoreServicesBuilderList() {
      return getCoreServicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cart.client.modules.serviceability.Service, cart.client.modules.serviceability.Service.Builder, cart.client.modules.serviceability.ServiceOrBuilder> 
        getCoreServicesFieldBuilder() {
      if (coreServicesBuilder_ == null) {
        coreServicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cart.client.modules.serviceability.Service, cart.client.modules.serviceability.Service.Builder, cart.client.modules.serviceability.ServiceOrBuilder>(
                coreServices_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        coreServices_ = null;
      }
      return coreServicesBuilder_;
    }

    private java.util.List<cart.client.modules.serviceability.Service> addOnServices_ =
      java.util.Collections.emptyList();
    private void ensureAddOnServicesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        addOnServices_ = new java.util.ArrayList<cart.client.modules.serviceability.Service>(addOnServices_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cart.client.modules.serviceability.Service, cart.client.modules.serviceability.Service.Builder, cart.client.modules.serviceability.ServiceOrBuilder> addOnServicesBuilder_;

    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public java.util.List<cart.client.modules.serviceability.Service> getAddOnServicesList() {
      if (addOnServicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(addOnServices_);
      } else {
        return addOnServicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public int getAddOnServicesCount() {
      if (addOnServicesBuilder_ == null) {
        return addOnServices_.size();
      } else {
        return addOnServicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public cart.client.modules.serviceability.Service getAddOnServices(int index) {
      if (addOnServicesBuilder_ == null) {
        return addOnServices_.get(index);
      } else {
        return addOnServicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder setAddOnServices(
        int index, cart.client.modules.serviceability.Service value) {
      if (addOnServicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddOnServicesIsMutable();
        addOnServices_.set(index, value);
        onChanged();
      } else {
        addOnServicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder setAddOnServices(
        int index, cart.client.modules.serviceability.Service.Builder builderForValue) {
      if (addOnServicesBuilder_ == null) {
        ensureAddOnServicesIsMutable();
        addOnServices_.set(index, builderForValue.build());
        onChanged();
      } else {
        addOnServicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder addAddOnServices(cart.client.modules.serviceability.Service value) {
      if (addOnServicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddOnServicesIsMutable();
        addOnServices_.add(value);
        onChanged();
      } else {
        addOnServicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder addAddOnServices(
        int index, cart.client.modules.serviceability.Service value) {
      if (addOnServicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddOnServicesIsMutable();
        addOnServices_.add(index, value);
        onChanged();
      } else {
        addOnServicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder addAddOnServices(
        cart.client.modules.serviceability.Service.Builder builderForValue) {
      if (addOnServicesBuilder_ == null) {
        ensureAddOnServicesIsMutable();
        addOnServices_.add(builderForValue.build());
        onChanged();
      } else {
        addOnServicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder addAddOnServices(
        int index, cart.client.modules.serviceability.Service.Builder builderForValue) {
      if (addOnServicesBuilder_ == null) {
        ensureAddOnServicesIsMutable();
        addOnServices_.add(index, builderForValue.build());
        onChanged();
      } else {
        addOnServicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder addAllAddOnServices(
        java.lang.Iterable<? extends cart.client.modules.serviceability.Service> values) {
      if (addOnServicesBuilder_ == null) {
        ensureAddOnServicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addOnServices_);
        onChanged();
      } else {
        addOnServicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder clearAddOnServices() {
      if (addOnServicesBuilder_ == null) {
        addOnServices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        addOnServicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public Builder removeAddOnServices(int index) {
      if (addOnServicesBuilder_ == null) {
        ensureAddOnServicesIsMutable();
        addOnServices_.remove(index);
        onChanged();
      } else {
        addOnServicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public cart.client.modules.serviceability.Service.Builder getAddOnServicesBuilder(
        int index) {
      return getAddOnServicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public cart.client.modules.serviceability.ServiceOrBuilder getAddOnServicesOrBuilder(
        int index) {
      if (addOnServicesBuilder_ == null) {
        return addOnServices_.get(index);  } else {
        return addOnServicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public java.util.List<? extends cart.client.modules.serviceability.ServiceOrBuilder> 
         getAddOnServicesOrBuilderList() {
      if (addOnServicesBuilder_ != null) {
        return addOnServicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(addOnServices_);
      }
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public cart.client.modules.serviceability.Service.Builder addAddOnServicesBuilder() {
      return getAddOnServicesFieldBuilder().addBuilder(
          cart.client.modules.serviceability.Service.getDefaultInstance());
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public cart.client.modules.serviceability.Service.Builder addAddOnServicesBuilder(
        int index) {
      return getAddOnServicesFieldBuilder().addBuilder(
          index, cart.client.modules.serviceability.Service.getDefaultInstance());
    }
    /**
     * <code>repeated .cart.client.modules.serviceability.Service addOnServices = 2;</code>
     */
    public java.util.List<cart.client.modules.serviceability.Service.Builder> 
         getAddOnServicesBuilderList() {
      return getAddOnServicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cart.client.modules.serviceability.Service, cart.client.modules.serviceability.Service.Builder, cart.client.modules.serviceability.ServiceOrBuilder> 
        getAddOnServicesFieldBuilder() {
      if (addOnServicesBuilder_ == null) {
        addOnServicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cart.client.modules.serviceability.Service, cart.client.modules.serviceability.Service.Builder, cart.client.modules.serviceability.ServiceOrBuilder>(
                addOnServices_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        addOnServices_ = null;
      }
      return addOnServicesBuilder_;
    }

    private cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cart.client.modules.serviceability.ServiceabilityInfoMetaData, cart.client.modules.serviceability.ServiceabilityInfoMetaData.Builder, cart.client.modules.serviceability.ServiceabilityInfoMetaDataOrBuilder> metaDataBuilder_;
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public boolean hasMetaData() {
      return metaDataBuilder_ != null || metaData_ != null;
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public cart.client.modules.serviceability.ServiceabilityInfoMetaData getMetaData() {
      if (metaDataBuilder_ == null) {
        return metaData_ == null ? cart.client.modules.serviceability.ServiceabilityInfoMetaData.getDefaultInstance() : metaData_;
      } else {
        return metaDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public Builder setMetaData(cart.client.modules.serviceability.ServiceabilityInfoMetaData value) {
      if (metaDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metaData_ = value;
        onChanged();
      } else {
        metaDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public Builder setMetaData(
        cart.client.modules.serviceability.ServiceabilityInfoMetaData.Builder builderForValue) {
      if (metaDataBuilder_ == null) {
        metaData_ = builderForValue.build();
        onChanged();
      } else {
        metaDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public Builder mergeMetaData(cart.client.modules.serviceability.ServiceabilityInfoMetaData value) {
      if (metaDataBuilder_ == null) {
        if (metaData_ != null) {
          metaData_ =
            cart.client.modules.serviceability.ServiceabilityInfoMetaData.newBuilder(metaData_).mergeFrom(value).buildPartial();
        } else {
          metaData_ = value;
        }
        onChanged();
      } else {
        metaDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public Builder clearMetaData() {
      if (metaDataBuilder_ == null) {
        metaData_ = null;
        onChanged();
      } else {
        metaData_ = null;
        metaDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public cart.client.modules.serviceability.ServiceabilityInfoMetaData.Builder getMetaDataBuilder() {
      
      onChanged();
      return getMetaDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    public cart.client.modules.serviceability.ServiceabilityInfoMetaDataOrBuilder getMetaDataOrBuilder() {
      if (metaDataBuilder_ != null) {
        return metaDataBuilder_.getMessageOrBuilder();
      } else {
        return metaData_ == null ?
            cart.client.modules.serviceability.ServiceabilityInfoMetaData.getDefaultInstance() : metaData_;
      }
    }
    /**
     * <code>.cart.client.modules.serviceability.ServiceabilityInfoMetaData metaData = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cart.client.modules.serviceability.ServiceabilityInfoMetaData, cart.client.modules.serviceability.ServiceabilityInfoMetaData.Builder, cart.client.modules.serviceability.ServiceabilityInfoMetaDataOrBuilder> 
        getMetaDataFieldBuilder() {
      if (metaDataBuilder_ == null) {
        metaDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cart.client.modules.serviceability.ServiceabilityInfoMetaData, cart.client.modules.serviceability.ServiceabilityInfoMetaData.Builder, cart.client.modules.serviceability.ServiceabilityInfoMetaDataOrBuilder>(
                getMetaData(),
                getParentForChildren(),
                isClean());
        metaData_ = null;
      }
      return metaDataBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cart.client.modules.serviceability.ServiceAbilityInfo)
  }

  // @@protoc_insertion_point(class_scope:cart.client.modules.serviceability.ServiceAbilityInfo)
  private static final cart.client.modules.serviceability.ServiceAbilityInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cart.client.modules.serviceability.ServiceAbilityInfo();
  }

  public static cart.client.modules.serviceability.ServiceAbilityInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceAbilityInfo>
      PARSER = new com.google.protobuf.AbstractParser<ServiceAbilityInfo>() {
    public ServiceAbilityInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceAbilityInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServiceAbilityInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceAbilityInfo> getParserForType() {
    return PARSER;
  }

  public cart.client.modules.serviceability.ServiceAbilityInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

