// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/endpoints/common/meta/cartitem/Quantity.proto

package cart.client.endpoints.common.meta.cartitem;

public final class QuantityOuterClass {
  private QuantityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_endpoints_common_meta_cartitem_Quantity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_endpoints_common_meta_cartitem_Quantity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9cart/client/endpoints/common/meta/cart" +
      "item/Quantity.proto\022*cart.client.endpoin" +
      "ts.common.meta.cartitem\"0\n\010Quantity\022\r\n\005v" +
      "alue\030\001 \001(\005\022\025\n\rINIT_QUANTITY\030\002 \001(\005B.\n*car" +
      "t.client.endpoints.common.meta.cartitemP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cart_client_endpoints_common_meta_cartitem_Quantity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_endpoints_common_meta_cartitem_Quantity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_endpoints_common_meta_cartitem_Quantity_descriptor,
        new java.lang.String[] { "Value", "INITQUANTITY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
