// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/serviceability/DataBag.proto

package cart.client.modules.serviceability;

public final class DataBagOuterClass {
  private DataBagOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_modules_serviceability_DataBag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_modules_serviceability_DataBag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0cart/client/modules/serviceability/Dat" +
      "aBag.proto\022\"cart.client.modules.servicea" +
      "bility\032,cart/client/modules/serviceabili" +
      "ty/Tag.proto\"\332\002\n\007DataBag\022\013\n\003sla\030\001 \001(\005\022\034\n" +
      "\024shipmentMovementType\030\002 \001(\t\022\014\n\004cost\030\003 \001(" +
      "\001\022\021\n\tavailable\030\004 \001(\010\022\021\n\tslotRefId\030\005 \001(\t\022" +
      "\023\n\013sourceRefId\030\006 \001(\t\0225\n\004tags\030\007 \001(\0132\'.car" +
      "t.client.modules.serviceability.Tag\022\022\n\ns" +
      "ourceEpst\030\010 \001(\t\022\022\n\nsourceLpst\030\t \001(\t\022\017\n\007e" +
      "ndTime\030\n \001(\t\022\021\n\tstartTime\030\013 \001(\t\022\024\n\014booki" +
      "ngRefId\030\014 \001(\t\022\020\n\010naReason\030\r \001(\t\022\030\n\020dplus" +
      "iGuaranteed\030\016 \001(\010\022\026\n\016dplusiEligible\030\017 \001(" +
      "\010B&\n\"cart.client.modules.serviceabilityP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cart.client.modules.serviceability.TagOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cart_client_modules_serviceability_DataBag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_modules_serviceability_DataBag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_modules_serviceability_DataBag_descriptor,
        new java.lang.String[] { "Sla", "ShipmentMovementType", "Cost", "Available", "SlotRefId", "SourceRefId", "Tags", "SourceEpst", "SourceLpst", "EndTime", "StartTime", "BookingRefId", "NaReason", "DplusiGuaranteed", "DplusiEligible", });
    cart.client.modules.serviceability.TagOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
