// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/serviceability/DataBag.proto

package cart.client.modules.serviceability;

/**
 * Protobuf type {@code cart.client.modules.serviceability.DataBag}
 */
public  final class DataBag extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cart.client.modules.serviceability.DataBag)
    DataBagOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataBag.newBuilder() to construct.
  private DataBag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataBag() {
    sla_ = 0;
    shipmentMovementType_ = "";
    cost_ = 0D;
    available_ = false;
    slotRefId_ = "";
    sourceRefId_ = "";
    sourceEpst_ = "";
    sourceLpst_ = "";
    endTime_ = "";
    startTime_ = "";
    bookingRefId_ = "";
    naReason_ = "";
    dplusiGuaranteed_ = false;
    dplusiEligible_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DataBag(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            sla_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            shipmentMovementType_ = s;
            break;
          }
          case 25: {

            cost_ = input.readDouble();
            break;
          }
          case 32: {

            available_ = input.readBool();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            slotRefId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceRefId_ = s;
            break;
          }
          case 58: {
            cart.client.modules.serviceability.Tag.Builder subBuilder = null;
            if (tags_ != null) {
              subBuilder = tags_.toBuilder();
            }
            tags_ = input.readMessage(cart.client.modules.serviceability.Tag.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tags_);
              tags_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceEpst_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceLpst_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            endTime_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            startTime_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            bookingRefId_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            naReason_ = s;
            break;
          }
          case 112: {

            dplusiGuaranteed_ = input.readBool();
            break;
          }
          case 120: {

            dplusiEligible_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cart.client.modules.serviceability.DataBagOuterClass.internal_static_cart_client_modules_serviceability_DataBag_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cart.client.modules.serviceability.DataBagOuterClass.internal_static_cart_client_modules_serviceability_DataBag_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cart.client.modules.serviceability.DataBag.class, cart.client.modules.serviceability.DataBag.Builder.class);
  }

  public static final int SLA_FIELD_NUMBER = 1;
  private int sla_;
  /**
   * <code>int32 sla = 1;</code>
   */
  public int getSla() {
    return sla_;
  }

  public static final int SHIPMENTMOVEMENTTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object shipmentMovementType_;
  /**
   * <code>string shipmentMovementType = 2;</code>
   */
  public java.lang.String getShipmentMovementType() {
    java.lang.Object ref = shipmentMovementType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shipmentMovementType_ = s;
      return s;
    }
  }
  /**
   * <code>string shipmentMovementType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getShipmentMovementTypeBytes() {
    java.lang.Object ref = shipmentMovementType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shipmentMovementType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COST_FIELD_NUMBER = 3;
  private double cost_;
  /**
   * <code>double cost = 3;</code>
   */
  public double getCost() {
    return cost_;
  }

  public static final int AVAILABLE_FIELD_NUMBER = 4;
  private boolean available_;
  /**
   * <code>bool available = 4;</code>
   */
  public boolean getAvailable() {
    return available_;
  }

  public static final int SLOTREFID_FIELD_NUMBER = 5;
  private volatile java.lang.Object slotRefId_;
  /**
   * <code>string slotRefId = 5;</code>
   */
  public java.lang.String getSlotRefId() {
    java.lang.Object ref = slotRefId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slotRefId_ = s;
      return s;
    }
  }
  /**
   * <code>string slotRefId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSlotRefIdBytes() {
    java.lang.Object ref = slotRefId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slotRefId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEREFID_FIELD_NUMBER = 6;
  private volatile java.lang.Object sourceRefId_;
  /**
   * <code>string sourceRefId = 6;</code>
   */
  public java.lang.String getSourceRefId() {
    java.lang.Object ref = sourceRefId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceRefId_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceRefId = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSourceRefIdBytes() {
    java.lang.Object ref = sourceRefId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceRefId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 7;
  private cart.client.modules.serviceability.Tag tags_;
  /**
   * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
   */
  public boolean hasTags() {
    return tags_ != null;
  }
  /**
   * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
   */
  public cart.client.modules.serviceability.Tag getTags() {
    return tags_ == null ? cart.client.modules.serviceability.Tag.getDefaultInstance() : tags_;
  }
  /**
   * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
   */
  public cart.client.modules.serviceability.TagOrBuilder getTagsOrBuilder() {
    return getTags();
  }

  public static final int SOURCEEPST_FIELD_NUMBER = 8;
  private volatile java.lang.Object sourceEpst_;
  /**
   * <code>string sourceEpst = 8;</code>
   */
  public java.lang.String getSourceEpst() {
    java.lang.Object ref = sourceEpst_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceEpst_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceEpst = 8;</code>
   */
  public com.google.protobuf.ByteString
      getSourceEpstBytes() {
    java.lang.Object ref = sourceEpst_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceEpst_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCELPST_FIELD_NUMBER = 9;
  private volatile java.lang.Object sourceLpst_;
  /**
   * <code>string sourceLpst = 9;</code>
   */
  public java.lang.String getSourceLpst() {
    java.lang.Object ref = sourceLpst_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceLpst_ = s;
      return s;
    }
  }
  /**
   * <code>string sourceLpst = 9;</code>
   */
  public com.google.protobuf.ByteString
      getSourceLpstBytes() {
    java.lang.Object ref = sourceLpst_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceLpst_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDTIME_FIELD_NUMBER = 10;
  private volatile java.lang.Object endTime_;
  /**
   * <code>string endTime = 10;</code>
   */
  public java.lang.String getEndTime() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endTime_ = s;
      return s;
    }
  }
  /**
   * <code>string endTime = 10;</code>
   */
  public com.google.protobuf.ByteString
      getEndTimeBytes() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTTIME_FIELD_NUMBER = 11;
  private volatile java.lang.Object startTime_;
  /**
   * <code>string startTime = 11;</code>
   */
  public java.lang.String getStartTime() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startTime_ = s;
      return s;
    }
  }
  /**
   * <code>string startTime = 11;</code>
   */
  public com.google.protobuf.ByteString
      getStartTimeBytes() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOKINGREFID_FIELD_NUMBER = 12;
  private volatile java.lang.Object bookingRefId_;
  /**
   * <code>string bookingRefId = 12;</code>
   */
  public java.lang.String getBookingRefId() {
    java.lang.Object ref = bookingRefId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bookingRefId_ = s;
      return s;
    }
  }
  /**
   * <code>string bookingRefId = 12;</code>
   */
  public com.google.protobuf.ByteString
      getBookingRefIdBytes() {
    java.lang.Object ref = bookingRefId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bookingRefId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAREASON_FIELD_NUMBER = 13;
  private volatile java.lang.Object naReason_;
  /**
   * <code>string naReason = 13;</code>
   */
  public java.lang.String getNaReason() {
    java.lang.Object ref = naReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      naReason_ = s;
      return s;
    }
  }
  /**
   * <code>string naReason = 13;</code>
   */
  public com.google.protobuf.ByteString
      getNaReasonBytes() {
    java.lang.Object ref = naReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      naReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DPLUSIGUARANTEED_FIELD_NUMBER = 14;
  private boolean dplusiGuaranteed_;
  /**
   * <code>bool dplusiGuaranteed = 14;</code>
   */
  public boolean getDplusiGuaranteed() {
    return dplusiGuaranteed_;
  }

  public static final int DPLUSIELIGIBLE_FIELD_NUMBER = 15;
  private boolean dplusiEligible_;
  /**
   * <code>bool dplusiEligible = 15;</code>
   */
  public boolean getDplusiEligible() {
    return dplusiEligible_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sla_ != 0) {
      output.writeInt32(1, sla_);
    }
    if (!getShipmentMovementTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, shipmentMovementType_);
    }
    if (cost_ != 0D) {
      output.writeDouble(3, cost_);
    }
    if (available_ != false) {
      output.writeBool(4, available_);
    }
    if (!getSlotRefIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, slotRefId_);
    }
    if (!getSourceRefIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sourceRefId_);
    }
    if (tags_ != null) {
      output.writeMessage(7, getTags());
    }
    if (!getSourceEpstBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sourceEpst_);
    }
    if (!getSourceLpstBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sourceLpst_);
    }
    if (!getEndTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, endTime_);
    }
    if (!getStartTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, startTime_);
    }
    if (!getBookingRefIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, bookingRefId_);
    }
    if (!getNaReasonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, naReason_);
    }
    if (dplusiGuaranteed_ != false) {
      output.writeBool(14, dplusiGuaranteed_);
    }
    if (dplusiEligible_ != false) {
      output.writeBool(15, dplusiEligible_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sla_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sla_);
    }
    if (!getShipmentMovementTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, shipmentMovementType_);
    }
    if (cost_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, cost_);
    }
    if (available_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, available_);
    }
    if (!getSlotRefIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, slotRefId_);
    }
    if (!getSourceRefIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sourceRefId_);
    }
    if (tags_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTags());
    }
    if (!getSourceEpstBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sourceEpst_);
    }
    if (!getSourceLpstBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sourceLpst_);
    }
    if (!getEndTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, endTime_);
    }
    if (!getStartTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, startTime_);
    }
    if (!getBookingRefIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, bookingRefId_);
    }
    if (!getNaReasonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, naReason_);
    }
    if (dplusiGuaranteed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, dplusiGuaranteed_);
    }
    if (dplusiEligible_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(15, dplusiEligible_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cart.client.modules.serviceability.DataBag)) {
      return super.equals(obj);
    }
    cart.client.modules.serviceability.DataBag other = (cart.client.modules.serviceability.DataBag) obj;

    boolean result = true;
    result = result && (getSla()
        == other.getSla());
    result = result && getShipmentMovementType()
        .equals(other.getShipmentMovementType());
    result = result && (
        java.lang.Double.doubleToLongBits(getCost())
        == java.lang.Double.doubleToLongBits(
            other.getCost()));
    result = result && (getAvailable()
        == other.getAvailable());
    result = result && getSlotRefId()
        .equals(other.getSlotRefId());
    result = result && getSourceRefId()
        .equals(other.getSourceRefId());
    result = result && (hasTags() == other.hasTags());
    if (hasTags()) {
      result = result && getTags()
          .equals(other.getTags());
    }
    result = result && getSourceEpst()
        .equals(other.getSourceEpst());
    result = result && getSourceLpst()
        .equals(other.getSourceLpst());
    result = result && getEndTime()
        .equals(other.getEndTime());
    result = result && getStartTime()
        .equals(other.getStartTime());
    result = result && getBookingRefId()
        .equals(other.getBookingRefId());
    result = result && getNaReason()
        .equals(other.getNaReason());
    result = result && (getDplusiGuaranteed()
        == other.getDplusiGuaranteed());
    result = result && (getDplusiEligible()
        == other.getDplusiEligible());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SLA_FIELD_NUMBER;
    hash = (53 * hash) + getSla();
    hash = (37 * hash) + SHIPMENTMOVEMENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getShipmentMovementType().hashCode();
    hash = (37 * hash) + COST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCost()));
    hash = (37 * hash) + AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAvailable());
    hash = (37 * hash) + SLOTREFID_FIELD_NUMBER;
    hash = (53 * hash) + getSlotRefId().hashCode();
    hash = (37 * hash) + SOURCEREFID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceRefId().hashCode();
    if (hasTags()) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTags().hashCode();
    }
    hash = (37 * hash) + SOURCEEPST_FIELD_NUMBER;
    hash = (53 * hash) + getSourceEpst().hashCode();
    hash = (37 * hash) + SOURCELPST_FIELD_NUMBER;
    hash = (53 * hash) + getSourceLpst().hashCode();
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getEndTime().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getStartTime().hashCode();
    hash = (37 * hash) + BOOKINGREFID_FIELD_NUMBER;
    hash = (53 * hash) + getBookingRefId().hashCode();
    hash = (37 * hash) + NAREASON_FIELD_NUMBER;
    hash = (53 * hash) + getNaReason().hashCode();
    hash = (37 * hash) + DPLUSIGUARANTEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDplusiGuaranteed());
    hash = (37 * hash) + DPLUSIELIGIBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDplusiEligible());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cart.client.modules.serviceability.DataBag parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.serviceability.DataBag parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cart.client.modules.serviceability.DataBag parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.serviceability.DataBag parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cart.client.modules.serviceability.DataBag prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cart.client.modules.serviceability.DataBag}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cart.client.modules.serviceability.DataBag)
      cart.client.modules.serviceability.DataBagOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cart.client.modules.serviceability.DataBagOuterClass.internal_static_cart_client_modules_serviceability_DataBag_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cart.client.modules.serviceability.DataBagOuterClass.internal_static_cart_client_modules_serviceability_DataBag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cart.client.modules.serviceability.DataBag.class, cart.client.modules.serviceability.DataBag.Builder.class);
    }

    // Construct using cart.client.modules.serviceability.DataBag.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      sla_ = 0;

      shipmentMovementType_ = "";

      cost_ = 0D;

      available_ = false;

      slotRefId_ = "";

      sourceRefId_ = "";

      if (tagsBuilder_ == null) {
        tags_ = null;
      } else {
        tags_ = null;
        tagsBuilder_ = null;
      }
      sourceEpst_ = "";

      sourceLpst_ = "";

      endTime_ = "";

      startTime_ = "";

      bookingRefId_ = "";

      naReason_ = "";

      dplusiGuaranteed_ = false;

      dplusiEligible_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cart.client.modules.serviceability.DataBagOuterClass.internal_static_cart_client_modules_serviceability_DataBag_descriptor;
    }

    public cart.client.modules.serviceability.DataBag getDefaultInstanceForType() {
      return cart.client.modules.serviceability.DataBag.getDefaultInstance();
    }

    public cart.client.modules.serviceability.DataBag build() {
      cart.client.modules.serviceability.DataBag result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cart.client.modules.serviceability.DataBag buildPartial() {
      cart.client.modules.serviceability.DataBag result = new cart.client.modules.serviceability.DataBag(this);
      result.sla_ = sla_;
      result.shipmentMovementType_ = shipmentMovementType_;
      result.cost_ = cost_;
      result.available_ = available_;
      result.slotRefId_ = slotRefId_;
      result.sourceRefId_ = sourceRefId_;
      if (tagsBuilder_ == null) {
        result.tags_ = tags_;
      } else {
        result.tags_ = tagsBuilder_.build();
      }
      result.sourceEpst_ = sourceEpst_;
      result.sourceLpst_ = sourceLpst_;
      result.endTime_ = endTime_;
      result.startTime_ = startTime_;
      result.bookingRefId_ = bookingRefId_;
      result.naReason_ = naReason_;
      result.dplusiGuaranteed_ = dplusiGuaranteed_;
      result.dplusiEligible_ = dplusiEligible_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cart.client.modules.serviceability.DataBag) {
        return mergeFrom((cart.client.modules.serviceability.DataBag)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cart.client.modules.serviceability.DataBag other) {
      if (other == cart.client.modules.serviceability.DataBag.getDefaultInstance()) return this;
      if (other.getSla() != 0) {
        setSla(other.getSla());
      }
      if (!other.getShipmentMovementType().isEmpty()) {
        shipmentMovementType_ = other.shipmentMovementType_;
        onChanged();
      }
      if (other.getCost() != 0D) {
        setCost(other.getCost());
      }
      if (other.getAvailable() != false) {
        setAvailable(other.getAvailable());
      }
      if (!other.getSlotRefId().isEmpty()) {
        slotRefId_ = other.slotRefId_;
        onChanged();
      }
      if (!other.getSourceRefId().isEmpty()) {
        sourceRefId_ = other.sourceRefId_;
        onChanged();
      }
      if (other.hasTags()) {
        mergeTags(other.getTags());
      }
      if (!other.getSourceEpst().isEmpty()) {
        sourceEpst_ = other.sourceEpst_;
        onChanged();
      }
      if (!other.getSourceLpst().isEmpty()) {
        sourceLpst_ = other.sourceLpst_;
        onChanged();
      }
      if (!other.getEndTime().isEmpty()) {
        endTime_ = other.endTime_;
        onChanged();
      }
      if (!other.getStartTime().isEmpty()) {
        startTime_ = other.startTime_;
        onChanged();
      }
      if (!other.getBookingRefId().isEmpty()) {
        bookingRefId_ = other.bookingRefId_;
        onChanged();
      }
      if (!other.getNaReason().isEmpty()) {
        naReason_ = other.naReason_;
        onChanged();
      }
      if (other.getDplusiGuaranteed() != false) {
        setDplusiGuaranteed(other.getDplusiGuaranteed());
      }
      if (other.getDplusiEligible() != false) {
        setDplusiEligible(other.getDplusiEligible());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cart.client.modules.serviceability.DataBag parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cart.client.modules.serviceability.DataBag) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int sla_ ;
    /**
     * <code>int32 sla = 1;</code>
     */
    public int getSla() {
      return sla_;
    }
    /**
     * <code>int32 sla = 1;</code>
     */
    public Builder setSla(int value) {
      
      sla_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sla = 1;</code>
     */
    public Builder clearSla() {
      
      sla_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object shipmentMovementType_ = "";
    /**
     * <code>string shipmentMovementType = 2;</code>
     */
    public java.lang.String getShipmentMovementType() {
      java.lang.Object ref = shipmentMovementType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shipmentMovementType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string shipmentMovementType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getShipmentMovementTypeBytes() {
      java.lang.Object ref = shipmentMovementType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shipmentMovementType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string shipmentMovementType = 2;</code>
     */
    public Builder setShipmentMovementType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shipmentMovementType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string shipmentMovementType = 2;</code>
     */
    public Builder clearShipmentMovementType() {
      
      shipmentMovementType_ = getDefaultInstance().getShipmentMovementType();
      onChanged();
      return this;
    }
    /**
     * <code>string shipmentMovementType = 2;</code>
     */
    public Builder setShipmentMovementTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shipmentMovementType_ = value;
      onChanged();
      return this;
    }

    private double cost_ ;
    /**
     * <code>double cost = 3;</code>
     */
    public double getCost() {
      return cost_;
    }
    /**
     * <code>double cost = 3;</code>
     */
    public Builder setCost(double value) {
      
      cost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double cost = 3;</code>
     */
    public Builder clearCost() {
      
      cost_ = 0D;
      onChanged();
      return this;
    }

    private boolean available_ ;
    /**
     * <code>bool available = 4;</code>
     */
    public boolean getAvailable() {
      return available_;
    }
    /**
     * <code>bool available = 4;</code>
     */
    public Builder setAvailable(boolean value) {
      
      available_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool available = 4;</code>
     */
    public Builder clearAvailable() {
      
      available_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object slotRefId_ = "";
    /**
     * <code>string slotRefId = 5;</code>
     */
    public java.lang.String getSlotRefId() {
      java.lang.Object ref = slotRefId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slotRefId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slotRefId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSlotRefIdBytes() {
      java.lang.Object ref = slotRefId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slotRefId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slotRefId = 5;</code>
     */
    public Builder setSlotRefId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      slotRefId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string slotRefId = 5;</code>
     */
    public Builder clearSlotRefId() {
      
      slotRefId_ = getDefaultInstance().getSlotRefId();
      onChanged();
      return this;
    }
    /**
     * <code>string slotRefId = 5;</code>
     */
    public Builder setSlotRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      slotRefId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceRefId_ = "";
    /**
     * <code>string sourceRefId = 6;</code>
     */
    public java.lang.String getSourceRefId() {
      java.lang.Object ref = sourceRefId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceRefId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceRefId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSourceRefIdBytes() {
      java.lang.Object ref = sourceRefId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceRefId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceRefId = 6;</code>
     */
    public Builder setSourceRefId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceRefId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceRefId = 6;</code>
     */
    public Builder clearSourceRefId() {
      
      sourceRefId_ = getDefaultInstance().getSourceRefId();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceRefId = 6;</code>
     */
    public Builder setSourceRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceRefId_ = value;
      onChanged();
      return this;
    }

    private cart.client.modules.serviceability.Tag tags_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cart.client.modules.serviceability.Tag, cart.client.modules.serviceability.Tag.Builder, cart.client.modules.serviceability.TagOrBuilder> tagsBuilder_;
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public boolean hasTags() {
      return tagsBuilder_ != null || tags_ != null;
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public cart.client.modules.serviceability.Tag getTags() {
      if (tagsBuilder_ == null) {
        return tags_ == null ? cart.client.modules.serviceability.Tag.getDefaultInstance() : tags_;
      } else {
        return tagsBuilder_.getMessage();
      }
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public Builder setTags(cart.client.modules.serviceability.Tag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tags_ = value;
        onChanged();
      } else {
        tagsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public Builder setTags(
        cart.client.modules.serviceability.Tag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        tags_ = builderForValue.build();
        onChanged();
      } else {
        tagsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public Builder mergeTags(cart.client.modules.serviceability.Tag value) {
      if (tagsBuilder_ == null) {
        if (tags_ != null) {
          tags_ =
            cart.client.modules.serviceability.Tag.newBuilder(tags_).mergeFrom(value).buildPartial();
        } else {
          tags_ = value;
        }
        onChanged();
      } else {
        tagsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public Builder clearTags() {
      if (tagsBuilder_ == null) {
        tags_ = null;
        onChanged();
      } else {
        tags_ = null;
        tagsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public cart.client.modules.serviceability.Tag.Builder getTagsBuilder() {
      
      onChanged();
      return getTagsFieldBuilder().getBuilder();
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    public cart.client.modules.serviceability.TagOrBuilder getTagsOrBuilder() {
      if (tagsBuilder_ != null) {
        return tagsBuilder_.getMessageOrBuilder();
      } else {
        return tags_ == null ?
            cart.client.modules.serviceability.Tag.getDefaultInstance() : tags_;
      }
    }
    /**
     * <code>.cart.client.modules.serviceability.Tag tags = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cart.client.modules.serviceability.Tag, cart.client.modules.serviceability.Tag.Builder, cart.client.modules.serviceability.TagOrBuilder> 
        getTagsFieldBuilder() {
      if (tagsBuilder_ == null) {
        tagsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cart.client.modules.serviceability.Tag, cart.client.modules.serviceability.Tag.Builder, cart.client.modules.serviceability.TagOrBuilder>(
                getTags(),
                getParentForChildren(),
                isClean());
        tags_ = null;
      }
      return tagsBuilder_;
    }

    private java.lang.Object sourceEpst_ = "";
    /**
     * <code>string sourceEpst = 8;</code>
     */
    public java.lang.String getSourceEpst() {
      java.lang.Object ref = sourceEpst_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceEpst_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceEpst = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSourceEpstBytes() {
      java.lang.Object ref = sourceEpst_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceEpst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceEpst = 8;</code>
     */
    public Builder setSourceEpst(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceEpst_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceEpst = 8;</code>
     */
    public Builder clearSourceEpst() {
      
      sourceEpst_ = getDefaultInstance().getSourceEpst();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceEpst = 8;</code>
     */
    public Builder setSourceEpstBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceEpst_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceLpst_ = "";
    /**
     * <code>string sourceLpst = 9;</code>
     */
    public java.lang.String getSourceLpst() {
      java.lang.Object ref = sourceLpst_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceLpst_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sourceLpst = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSourceLpstBytes() {
      java.lang.Object ref = sourceLpst_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceLpst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sourceLpst = 9;</code>
     */
    public Builder setSourceLpst(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceLpst_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sourceLpst = 9;</code>
     */
    public Builder clearSourceLpst() {
      
      sourceLpst_ = getDefaultInstance().getSourceLpst();
      onChanged();
      return this;
    }
    /**
     * <code>string sourceLpst = 9;</code>
     */
    public Builder setSourceLpstBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceLpst_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endTime_ = "";
    /**
     * <code>string endTime = 10;</code>
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string endTime = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string endTime = 10;</code>
     */
    public Builder setEndTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string endTime = 10;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = getDefaultInstance().getEndTime();
      onChanged();
      return this;
    }
    /**
     * <code>string endTime = 10;</code>
     */
    public Builder setEndTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object startTime_ = "";
    /**
     * <code>string startTime = 11;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string startTime = 11;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string startTime = 11;</code>
     */
    public Builder setStartTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string startTime = 11;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = getDefaultInstance().getStartTime();
      onChanged();
      return this;
    }
    /**
     * <code>string startTime = 11;</code>
     */
    public Builder setStartTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      startTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bookingRefId_ = "";
    /**
     * <code>string bookingRefId = 12;</code>
     */
    public java.lang.String getBookingRefId() {
      java.lang.Object ref = bookingRefId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bookingRefId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bookingRefId = 12;</code>
     */
    public com.google.protobuf.ByteString
        getBookingRefIdBytes() {
      java.lang.Object ref = bookingRefId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingRefId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bookingRefId = 12;</code>
     */
    public Builder setBookingRefId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bookingRefId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bookingRefId = 12;</code>
     */
    public Builder clearBookingRefId() {
      
      bookingRefId_ = getDefaultInstance().getBookingRefId();
      onChanged();
      return this;
    }
    /**
     * <code>string bookingRefId = 12;</code>
     */
    public Builder setBookingRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bookingRefId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object naReason_ = "";
    /**
     * <code>string naReason = 13;</code>
     */
    public java.lang.String getNaReason() {
      java.lang.Object ref = naReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        naReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string naReason = 13;</code>
     */
    public com.google.protobuf.ByteString
        getNaReasonBytes() {
      java.lang.Object ref = naReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        naReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string naReason = 13;</code>
     */
    public Builder setNaReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      naReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string naReason = 13;</code>
     */
    public Builder clearNaReason() {
      
      naReason_ = getDefaultInstance().getNaReason();
      onChanged();
      return this;
    }
    /**
     * <code>string naReason = 13;</code>
     */
    public Builder setNaReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      naReason_ = value;
      onChanged();
      return this;
    }

    private boolean dplusiGuaranteed_ ;
    /**
     * <code>bool dplusiGuaranteed = 14;</code>
     */
    public boolean getDplusiGuaranteed() {
      return dplusiGuaranteed_;
    }
    /**
     * <code>bool dplusiGuaranteed = 14;</code>
     */
    public Builder setDplusiGuaranteed(boolean value) {
      
      dplusiGuaranteed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool dplusiGuaranteed = 14;</code>
     */
    public Builder clearDplusiGuaranteed() {
      
      dplusiGuaranteed_ = false;
      onChanged();
      return this;
    }

    private boolean dplusiEligible_ ;
    /**
     * <code>bool dplusiEligible = 15;</code>
     */
    public boolean getDplusiEligible() {
      return dplusiEligible_;
    }
    /**
     * <code>bool dplusiEligible = 15;</code>
     */
    public Builder setDplusiEligible(boolean value) {
      
      dplusiEligible_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool dplusiEligible = 15;</code>
     */
    public Builder clearDplusiEligible() {
      
      dplusiEligible_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cart.client.modules.serviceability.DataBag)
  }

  // @@protoc_insertion_point(class_scope:cart.client.modules.serviceability.DataBag)
  private static final cart.client.modules.serviceability.DataBag DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cart.client.modules.serviceability.DataBag();
  }

  public static cart.client.modules.serviceability.DataBag getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataBag>
      PARSER = new com.google.protobuf.AbstractParser<DataBag>() {
    public DataBag parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DataBag(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataBag> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataBag> getParserForType() {
    return PARSER;
  }

  public cart.client.modules.serviceability.DataBag getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

