// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/serviceability/MetaMessage.proto

package cart.client.modules.serviceability;

public interface MetaMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.client.modules.serviceability.MetaMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
