// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/disbursal/response/DisbursalApplicationMetaData.proto

package cart.client.modules.disbursal.response;

/**
 * Protobuf type {@code cart.client.modules.disbursal.response.DisbursalApplicationMetaData}
 */
public  final class DisbursalApplicationMetaData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cart.client.modules.disbursal.response.DisbursalApplicationMetaData)
    DisbursalApplicationMetaDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DisbursalApplicationMetaData.newBuilder() to construct.
  private DisbursalApplicationMetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DisbursalApplicationMetaData() {
    disbursalApplicationTypeEnum_ = 0;
    deferredDuration_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DisbursalApplicationMetaData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            disbursalApplicationTypeEnum_ = rawValue;
            break;
          }
          case 16: {

            deferredDuration_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cart.client.modules.disbursal.response.DisbursalApplicationMetaDataOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalApplicationMetaData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cart.client.modules.disbursal.response.DisbursalApplicationMetaDataOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalApplicationMetaData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cart.client.modules.disbursal.response.DisbursalApplicationMetaData.class, cart.client.modules.disbursal.response.DisbursalApplicationMetaData.Builder.class);
  }

  public static final int DISBURSALAPPLICATIONTYPEENUM_FIELD_NUMBER = 1;
  private int disbursalApplicationTypeEnum_;
  /**
   * <code>.cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum disbursalApplicationTypeEnum = 1;</code>
   */
  public int getDisbursalApplicationTypeEnumValue() {
    return disbursalApplicationTypeEnum_;
  }
  /**
   * <code>.cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum disbursalApplicationTypeEnum = 1;</code>
   */
  public cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum getDisbursalApplicationTypeEnum() {
    cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum result = cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum.valueOf(disbursalApplicationTypeEnum_);
    return result == null ? cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum.UNRECOGNIZED : result;
  }

  public static final int DEFERREDDURATION_FIELD_NUMBER = 2;
  private long deferredDuration_;
  /**
   * <code>int64 deferredDuration = 2;</code>
   */
  public long getDeferredDuration() {
    return deferredDuration_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (disbursalApplicationTypeEnum_ != cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum.INSTANT.getNumber()) {
      output.writeEnum(1, disbursalApplicationTypeEnum_);
    }
    if (deferredDuration_ != 0L) {
      output.writeInt64(2, deferredDuration_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (disbursalApplicationTypeEnum_ != cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum.INSTANT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, disbursalApplicationTypeEnum_);
    }
    if (deferredDuration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, deferredDuration_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cart.client.modules.disbursal.response.DisbursalApplicationMetaData)) {
      return super.equals(obj);
    }
    cart.client.modules.disbursal.response.DisbursalApplicationMetaData other = (cart.client.modules.disbursal.response.DisbursalApplicationMetaData) obj;

    boolean result = true;
    result = result && disbursalApplicationTypeEnum_ == other.disbursalApplicationTypeEnum_;
    result = result && (getDeferredDuration()
        == other.getDeferredDuration());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISBURSALAPPLICATIONTYPEENUM_FIELD_NUMBER;
    hash = (53 * hash) + disbursalApplicationTypeEnum_;
    hash = (37 * hash) + DEFERREDDURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeferredDuration());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cart.client.modules.disbursal.response.DisbursalApplicationMetaData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cart.client.modules.disbursal.response.DisbursalApplicationMetaData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cart.client.modules.disbursal.response.DisbursalApplicationMetaData)
      cart.client.modules.disbursal.response.DisbursalApplicationMetaDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cart.client.modules.disbursal.response.DisbursalApplicationMetaDataOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalApplicationMetaData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cart.client.modules.disbursal.response.DisbursalApplicationMetaDataOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalApplicationMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cart.client.modules.disbursal.response.DisbursalApplicationMetaData.class, cart.client.modules.disbursal.response.DisbursalApplicationMetaData.Builder.class);
    }

    // Construct using cart.client.modules.disbursal.response.DisbursalApplicationMetaData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      disbursalApplicationTypeEnum_ = 0;

      deferredDuration_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cart.client.modules.disbursal.response.DisbursalApplicationMetaDataOuterClass.internal_static_cart_client_modules_disbursal_response_DisbursalApplicationMetaData_descriptor;
    }

    public cart.client.modules.disbursal.response.DisbursalApplicationMetaData getDefaultInstanceForType() {
      return cart.client.modules.disbursal.response.DisbursalApplicationMetaData.getDefaultInstance();
    }

    public cart.client.modules.disbursal.response.DisbursalApplicationMetaData build() {
      cart.client.modules.disbursal.response.DisbursalApplicationMetaData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cart.client.modules.disbursal.response.DisbursalApplicationMetaData buildPartial() {
      cart.client.modules.disbursal.response.DisbursalApplicationMetaData result = new cart.client.modules.disbursal.response.DisbursalApplicationMetaData(this);
      result.disbursalApplicationTypeEnum_ = disbursalApplicationTypeEnum_;
      result.deferredDuration_ = deferredDuration_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cart.client.modules.disbursal.response.DisbursalApplicationMetaData) {
        return mergeFrom((cart.client.modules.disbursal.response.DisbursalApplicationMetaData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cart.client.modules.disbursal.response.DisbursalApplicationMetaData other) {
      if (other == cart.client.modules.disbursal.response.DisbursalApplicationMetaData.getDefaultInstance()) return this;
      if (other.disbursalApplicationTypeEnum_ != 0) {
        setDisbursalApplicationTypeEnumValue(other.getDisbursalApplicationTypeEnumValue());
      }
      if (other.getDeferredDuration() != 0L) {
        setDeferredDuration(other.getDeferredDuration());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cart.client.modules.disbursal.response.DisbursalApplicationMetaData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cart.client.modules.disbursal.response.DisbursalApplicationMetaData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int disbursalApplicationTypeEnum_ = 0;
    /**
     * <code>.cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum disbursalApplicationTypeEnum = 1;</code>
     */
    public int getDisbursalApplicationTypeEnumValue() {
      return disbursalApplicationTypeEnum_;
    }
    /**
     * <code>.cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum disbursalApplicationTypeEnum = 1;</code>
     */
    public Builder setDisbursalApplicationTypeEnumValue(int value) {
      disbursalApplicationTypeEnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum disbursalApplicationTypeEnum = 1;</code>
     */
    public cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum getDisbursalApplicationTypeEnum() {
      cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum result = cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum.valueOf(disbursalApplicationTypeEnum_);
      return result == null ? cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum disbursalApplicationTypeEnum = 1;</code>
     */
    public Builder setDisbursalApplicationTypeEnum(cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      disbursalApplicationTypeEnum_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.cart.client.modules.disbursal.enums.DisbursalApplicationTypeEnum disbursalApplicationTypeEnum = 1;</code>
     */
    public Builder clearDisbursalApplicationTypeEnum() {
      
      disbursalApplicationTypeEnum_ = 0;
      onChanged();
      return this;
    }

    private long deferredDuration_ ;
    /**
     * <code>int64 deferredDuration = 2;</code>
     */
    public long getDeferredDuration() {
      return deferredDuration_;
    }
    /**
     * <code>int64 deferredDuration = 2;</code>
     */
    public Builder setDeferredDuration(long value) {
      
      deferredDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 deferredDuration = 2;</code>
     */
    public Builder clearDeferredDuration() {
      
      deferredDuration_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cart.client.modules.disbursal.response.DisbursalApplicationMetaData)
  }

  // @@protoc_insertion_point(class_scope:cart.client.modules.disbursal.response.DisbursalApplicationMetaData)
  private static final cart.client.modules.disbursal.response.DisbursalApplicationMetaData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cart.client.modules.disbursal.response.DisbursalApplicationMetaData();
  }

  public static cart.client.modules.disbursal.response.DisbursalApplicationMetaData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DisbursalApplicationMetaData>
      PARSER = new com.google.protobuf.AbstractParser<DisbursalApplicationMetaData>() {
    public DisbursalApplicationMetaData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DisbursalApplicationMetaData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DisbursalApplicationMetaData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DisbursalApplicationMetaData> getParserForType() {
    return PARSER;
  }

  public cart.client.modules.disbursal.response.DisbursalApplicationMetaData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

