// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/disbursal/response/MessageText.proto

package cart.client.modules.disbursal.response;

public interface MessageTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.client.modules.disbursal.response.MessageText)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string small = 1;</code>
   */
  java.lang.String getSmall();
  /**
   * <code>string small = 1;</code>
   */
  com.google.protobuf.ByteString
      getSmallBytes();

  /**
   * <code>string medium = 2;</code>
   */
  java.lang.String getMedium();
  /**
   * <code>string medium = 2;</code>
   */
  com.google.protobuf.ByteString
      getMediumBytes();

  /**
   * <code>string large = 3;</code>
   */
  java.lang.String getLarge();
  /**
   * <code>string large = 3;</code>
   */
  com.google.protobuf.ByteString
      getLargeBytes();
}
