// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/statemanagement/ItemState.proto

package cart.client.statemanagement;

/**
 * Protobuf enum {@code cart.client.statemanagement.ItemState}
 */
public enum ItemState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>COLD = 0;</code>
   */
  COLD(0),
  /**
   * <code>BUYABLE = 1;</code>
   */
  BUYABLE(1),
  /**
   * <code>SERVICE_FAILURE = 2;</code>
   */
  SERVICE_FAILURE(2),
  /**
   * <code>INTERMEDIATE = 3;</code>
   */
  INTERMEDIATE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>COLD = 0;</code>
   */
  public static final int COLD_VALUE = 0;
  /**
   * <code>BUYABLE = 1;</code>
   */
  public static final int BUYABLE_VALUE = 1;
  /**
   * <code>SERVICE_FAILURE = 2;</code>
   */
  public static final int SERVICE_FAILURE_VALUE = 2;
  /**
   * <code>INTERMEDIATE = 3;</code>
   */
  public static final int INTERMEDIATE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ItemState valueOf(int value) {
    return forNumber(value);
  }

  public static ItemState forNumber(int value) {
    switch (value) {
      case 0: return COLD;
      case 1: return BUYABLE;
      case 2: return SERVICE_FAILURE;
      case 3: return INTERMEDIATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ItemState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ItemState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ItemState>() {
          public ItemState findValueByNumber(int number) {
            return ItemState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return cart.client.statemanagement.ItemStateOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ItemState[] VALUES = values();

  public static ItemState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ItemState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:cart.client.statemanagement.ItemState)
}

