// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/adjustments/Adjustment.proto

package cart.client.modules.adjustments;

public interface AdjustmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.client.modules.adjustments.Adjustment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentType adjustmentType = 1;</code>
   */
  int getAdjustmentTypeValue();
  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentType adjustmentType = 1;</code>
   */
  cart.client.modules.adjustments.enums.AdjustmentType getAdjustmentType();

  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentImpact adjustmentImpact = 2;</code>
   */
  int getAdjustmentImpactValue();
  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentImpact adjustmentImpact = 2;</code>
   */
  cart.client.modules.adjustments.enums.AdjustmentImpact getAdjustmentImpact();

  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentFormat adjustmentFormat = 3;</code>
   */
  int getAdjustmentFormatValue();
  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentFormat adjustmentFormat = 3;</code>
   */
  cart.client.modules.adjustments.enums.AdjustmentFormat getAdjustmentFormat();

  /**
   * <code>.cart.client.modules.adjustments.Amount netApplicableAmount = 4;</code>
   */
  boolean hasNetApplicableAmount();
  /**
   * <code>.cart.client.modules.adjustments.Amount netApplicableAmount = 4;</code>
   */
  cart.client.modules.adjustments.Amount getNetApplicableAmount();
  /**
   * <code>.cart.client.modules.adjustments.Amount netApplicableAmount = 4;</code>
   */
  cart.client.modules.adjustments.AmountOrBuilder getNetApplicableAmountOrBuilder();

  /**
   * <code>.cart.client.modules.adjustments.Amount unitApplicableAmount = 5;</code>
   */
  boolean hasUnitApplicableAmount();
  /**
   * <code>.cart.client.modules.adjustments.Amount unitApplicableAmount = 5;</code>
   */
  cart.client.modules.adjustments.Amount getUnitApplicableAmount();
  /**
   * <code>.cart.client.modules.adjustments.Amount unitApplicableAmount = 5;</code>
   */
  cart.client.modules.adjustments.AmountOrBuilder getUnitApplicableAmountOrBuilder();

  /**
   * <code>string message = 6;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 6;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentSourceType sourceType = 7;</code>
   */
  int getSourceTypeValue();
  /**
   * <code>.cart.client.modules.adjustments.enums.AdjustmentSourceType sourceType = 7;</code>
   */
  cart.client.modules.adjustments.enums.AdjustmentSourceType getSourceType();

  /**
   * <code>string sourceRef = 8;</code>
   */
  java.lang.String getSourceRef();
  /**
   * <code>string sourceRef = 8;</code>
   */
  com.google.protobuf.ByteString
      getSourceRefBytes();

  /**
   * <code>string offerId = 9;</code>
   */
  java.lang.String getOfferId();
  /**
   * <code>string offerId = 9;</code>
   */
  com.google.protobuf.ByteString
      getOfferIdBytes();
}
