// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/modules/adjustments/GroupAdjustment.proto

package cart.client.modules.adjustments;

public final class GroupAdjustmentOuterClass {
  private GroupAdjustmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_modules_adjustments_GroupAdjustment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_modules_adjustments_GroupAdjustment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5cart/client/modules/adjustments/GroupA" +
      "djustment.proto\022\037cart.client.modules.adj" +
      "ustments\0320cart/client/modules/adjustment" +
      "s/Adjustment.proto\"V\n\017GroupAdjustment\022C\n" +
      "\016adjustmentList\030\001 \003(\0132+.cart.client.modu" +
      "les.adjustments.AdjustmentB#\n\037cart.clien" +
      "t.modules.adjustmentsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cart.client.modules.adjustments.AdjustmentOuterClass.getDescriptor(),
        }, assigner);
    internal_static_cart_client_modules_adjustments_GroupAdjustment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_modules_adjustments_GroupAdjustment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_modules_adjustments_GroupAdjustment_descriptor,
        new java.lang.String[] { "AdjustmentList", });
    cart.client.modules.adjustments.AdjustmentOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
