// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/flipkart/lockin/enums/Benefit.proto

package com.flipkart.lockin.enums;

public final class BenefitOuterClass {
  private BenefitOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'com/flipkart/lockin/enums/Benefit.prot" +
      "o\022\031com.flipkart.lockin.enums*w\n\007Benefit\022" +
      "\014\n\010FREESHIP\020\000\022\020\n\014PRIORITYSHIP\020\001\022\n\n\006EASAL" +
      "E\020\002\022\013\n\007EAFLASH\020\003\022\016\n\nPRIORITYCX\020\004\022\022\n\016EXTE" +
      "NDEDRETURN\020\005\022\017\n\013REWARDSTORE\020\006B\035\n\031com.fli" +
      "pkart.lockin.enumsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
