// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/client/endpoints/common/meta/cart/D2Rvalue.proto

package cart.client.endpoints.common.meta.cart;

public final class D2RvalueOuterClass {
  private D2RvalueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cart_client_endpoints_common_meta_cart_D2Rvalue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cart_client_endpoints_common_meta_cart_D2Rvalue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5cart/client/endpoints/common/meta/cart" +
      "/D2Rvalue.proto\022&cart.client.endpoints.c" +
      "ommon.meta.cart\"/\n\010D2Rvalue\022\021\n\tthreshold" +
      "\030\001 \001(\005\022\020\n\010distance\030\002 \001(\005B*\n&cart.client." +
      "endpoints.common.meta.cartP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cart_client_endpoints_common_meta_cart_D2Rvalue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cart_client_endpoints_common_meta_cart_D2Rvalue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cart_client_endpoints_common_meta_cart_D2Rvalue_descriptor,
        new java.lang.String[] { "Threshold", "Distance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
