// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map/type_map_message.proto

package com.flipkart.protobuf.ext.generator.map;

public final class TypeMapMessage {
  private TypeMapMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageWithTypeMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageWithTypeMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageWithTypeMap_stringToStringMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageWithTypeMap_stringToStringMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageWithTypeMap_stringToEnumMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageWithTypeMap_stringToEnumMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032map/type_map_message.proto\"\364\002\n\022Message" +
      "WithTypeMap\022E\n\021stringToStringMap\030\001 \003(\0132*" +
      ".MessageWithTypeMap.stringToStringMapEnt" +
      "ry\022A\n\017stringToEnumMap\030\002 \003(\0132(.MessageWit" +
      "hTypeMap.stringToEnumMapEntry\0324\n\026stringT" +
      "oStringMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t\032\235\001\n\024stringToEnumMapEntry\022\013\n\003key\030\001 \001(" +
      "\t\022F\n\005value\030\002 \001(\01627.MessageWithTypeMap.st" +
      "ringToEnumMapEntry.SampleEnumType\"0\n\016Sam" +
      "pleEnumType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WOR" +
      "K\020\002B+\n\'com.flipkart.protobuf.ext.generat" +
      "or.mapP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MessageWithTypeMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageWithTypeMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageWithTypeMap_descriptor,
        new java.lang.String[] { "StringToStringMap", "StringToEnumMap", });
    internal_static_MessageWithTypeMap_stringToStringMapEntry_descriptor =
      internal_static_MessageWithTypeMap_descriptor.getNestedTypes().get(0);
    internal_static_MessageWithTypeMap_stringToStringMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageWithTypeMap_stringToStringMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_MessageWithTypeMap_stringToEnumMapEntry_descriptor =
      internal_static_MessageWithTypeMap_descriptor.getNestedTypes().get(1);
    internal_static_MessageWithTypeMap_stringToEnumMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageWithTypeMap_stringToEnumMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
